// Code generated by assertgen. DO NOT EDIT.

package v2

import (
	v2 "github.com/fluxcd/helm-controller/api/v2"
	kustomize "github.com/fluxcd/pkg/apis/kustomize"
	meta "github.com/fluxcd/pkg/apis/meta"
	assert "github.com/mridang/wilhelm/assert"
	v11 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CommonMetadataAssertion is the assertion struct for CommonMetadata.
type CommonMetadataAssertion struct {
	Annotations assert.Opt[map[string]string]
	Labels      assert.Opt[map[string]string]
}

// IsAssertable marks CommonMetadataAssertion as an Assertable.
func (_ CommonMetadataAssertion) IsAssertable() {}

// CrossNamespaceObjectReferenceAssertion is the assertion struct for CrossNamespaceObjectReference.
type CrossNamespaceObjectReferenceAssertion struct {
	APIVersion assert.Opt[string]
	Kind       assert.Opt[string]
	Name       assert.Opt[string]
	Namespace  assert.Opt[string]
}

// IsAssertable marks CrossNamespaceObjectReferenceAssertion as an Assertable.
func (_ CrossNamespaceObjectReferenceAssertion) IsAssertable() {}

// CrossNamespaceSourceReferenceAssertion is the assertion struct for CrossNamespaceSourceReference.
type CrossNamespaceSourceReferenceAssertion struct {
	APIVersion assert.Opt[string]
	Kind       assert.Opt[string]
	Name       assert.Opt[string]
	Namespace  assert.Opt[string]
}

// IsAssertable marks CrossNamespaceSourceReferenceAssertion as an Assertable.
func (_ CrossNamespaceSourceReferenceAssertion) IsAssertable() {}

// DependencyReferenceAssertion is the assertion struct for DependencyReference.
type DependencyReferenceAssertion struct {
	Name      assert.Opt[string]
	Namespace assert.Opt[string]
	ReadyExpr assert.Opt[string]
}

// IsAssertable marks DependencyReferenceAssertion as an Assertable.
func (_ DependencyReferenceAssertion) IsAssertable() {}

// DriftDetectionAssertion is the assertion struct for DriftDetection.
type DriftDetectionAssertion struct {
	Mode   assert.Opt[v2.DriftDetectionMode]
	Ignore assert.Opt[[]IgnoreRuleAssertion]
}

// IsAssertable marks DriftDetectionAssertion as an Assertable.
func (_ DriftDetectionAssertion) IsAssertable() {}

// FilterAssertion is the assertion struct for Filter.
type FilterAssertion struct {
	Name    assert.Opt[string]
	Exclude assert.Opt[bool]
}

// IsAssertable marks FilterAssertion as an Assertable.
func (_ FilterAssertion) IsAssertable() {}

// GroupVersionAssertion is the assertion struct for GroupVersion.
type GroupVersionAssertion struct {
	Group   assert.Opt[string]
	Version assert.Opt[string]
}

// IsAssertable marks GroupVersionAssertion as an Assertable.
func (_ GroupVersionAssertion) IsAssertable() {}

// HelmChartTemplateAssertion is the assertion struct for HelmChartTemplate.
type HelmChartTemplateAssertion struct {
	ObjectMeta HelmChartTemplateObjectMetaAssertion
	Spec       HelmChartTemplateSpecAssertion
}

// IsAssertable marks HelmChartTemplateAssertion as an Assertable.
func (_ HelmChartTemplateAssertion) IsAssertable() {}

// HelmChartTemplateObjectMetaAssertion is the assertion struct for HelmChartTemplateObjectMeta.
type HelmChartTemplateObjectMetaAssertion struct {
	Labels      assert.Opt[map[string]string]
	Annotations assert.Opt[map[string]string]
}

// IsAssertable marks HelmChartTemplateObjectMetaAssertion as an Assertable.
func (_ HelmChartTemplateObjectMetaAssertion) IsAssertable() {}

// HelmChartTemplateSpecAssertion is the assertion struct for HelmChartTemplateSpec.
type HelmChartTemplateSpecAssertion struct {
	Chart                    assert.Opt[string]
	Version                  assert.Opt[string]
	SourceRef                CrossNamespaceObjectReferenceAssertion
	Interval                 assert.Opt[*v1.Duration]
	ReconcileStrategy        assert.Opt[string]
	ValuesFiles              assert.Opt[[]string]
	IgnoreMissingValuesFiles assert.Opt[bool]
	Verify                   HelmChartTemplateVerificationAssertion
}

// IsAssertable marks HelmChartTemplateSpecAssertion as an Assertable.
func (_ HelmChartTemplateSpecAssertion) IsAssertable() {}

// HelmChartTemplateVerificationAssertion is the assertion struct for HelmChartTemplateVerification.
type HelmChartTemplateVerificationAssertion struct {
	Provider  assert.Opt[string]
	SecretRef assert.Opt[*meta.LocalObjectReference]
}

// IsAssertable marks HelmChartTemplateVerificationAssertion as an Assertable.
func (_ HelmChartTemplateVerificationAssertion) IsAssertable() {}

// HelmReleaseAssertion is the assertion struct for HelmRelease.
type HelmReleaseAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       HelmReleaseSpecAssertion
	Status     assert.Opt[v2.HelmReleaseStatus]
}

// IsAssertable marks HelmReleaseAssertion as an Assertable.
func (_ HelmReleaseAssertion) IsAssertable() {}

// HelmReleaseSpecAssertion is the assertion struct for HelmReleaseSpec.
type HelmReleaseSpecAssertion struct {
	Chart              HelmChartTemplateAssertion
	ChartRef           CrossNamespaceSourceReferenceAssertion
	Interval           assert.Opt[v1.Duration]
	KubeConfig         assert.Opt[*meta.KubeConfigReference]
	Suspend            assert.Opt[bool]
	ReleaseName        assert.Opt[string]
	TargetNamespace    assert.Opt[string]
	StorageNamespace   assert.Opt[string]
	DependsOn          assert.Opt[[]DependencyReferenceAssertion]
	Timeout            assert.Opt[*v1.Duration]
	MaxHistory         assert.Opt[*int]
	ServiceAccountName assert.Opt[string]
	PersistentClient   assert.Opt[*bool]
	DriftDetection     DriftDetectionAssertion
	Install            InstallAssertion
	Upgrade            UpgradeAssertion
	Test               TestAssertion
	Rollback           RollbackAssertion
	Uninstall          UninstallAssertion
	ValuesFrom         assert.Opt[[]v2.ValuesReference]
	Values             assert.Opt[*v11.JSON]
	CommonMetadata     CommonMetadataAssertion
	PostRenderers      assert.Opt[[]PostRendererAssertion]
	WaitStrategy       WaitStrategyAssertion
	HealthCheckExprs   assert.Opt[[]kustomize.CustomHealthCheck]
}

// IsAssertable marks HelmReleaseSpecAssertion as an Assertable.
func (_ HelmReleaseSpecAssertion) IsAssertable() {}

// IgnoreRuleAssertion is the assertion struct for IgnoreRule.
type IgnoreRuleAssertion struct {
	Paths  assert.Opt[[]string]
	Target assert.Opt[*kustomize.Selector]
}

// IsAssertable marks IgnoreRuleAssertion as an Assertable.
func (_ IgnoreRuleAssertion) IsAssertable() {}

// InstallAssertion is the assertion struct for Install.
type InstallAssertion struct {
	Timeout                  assert.Opt[*v1.Duration]
	Strategy                 InstallStrategyAssertion
	Remediation              InstallRemediationAssertion
	DisableTakeOwnership     assert.Opt[bool]
	DisableWait              assert.Opt[bool]
	DisableWaitForJobs       assert.Opt[bool]
	DisableHooks             assert.Opt[bool]
	DisableOpenAPIValidation assert.Opt[bool]
	DisableSchemaValidation  assert.Opt[bool]
	Replace                  assert.Opt[bool]
	SkipCRDs                 assert.Opt[bool]
	CRDs                     assert.Opt[v2.CRDsPolicy]
	CreateNamespace          assert.Opt[bool]
	ServerSideApply          assert.Opt[*bool]
}

// IsAssertable marks InstallAssertion as an Assertable.
func (_ InstallAssertion) IsAssertable() {}

// InstallRemediationAssertion is the assertion struct for InstallRemediation.
type InstallRemediationAssertion struct {
	Retries              assert.Opt[int]
	IgnoreTestFailures   assert.Opt[*bool]
	RemediateLastFailure assert.Opt[*bool]
}

// IsAssertable marks InstallRemediationAssertion as an Assertable.
func (_ InstallRemediationAssertion) IsAssertable() {}

// InstallStrategyAssertion is the assertion struct for InstallStrategy.
type InstallStrategyAssertion struct {
	Name          assert.Opt[string]
	RetryInterval assert.Opt[*v1.Duration]
}

// IsAssertable marks InstallStrategyAssertion as an Assertable.
func (_ InstallStrategyAssertion) IsAssertable() {}

// KustomizeAssertion is the assertion struct for Kustomize.
type KustomizeAssertion struct {
	Patches assert.Opt[[]kustomize.Patch]
	Images  assert.Opt[[]kustomize.Image]
}

// IsAssertable marks KustomizeAssertion as an Assertable.
func (_ KustomizeAssertion) IsAssertable() {}

// PostRendererAssertion is the assertion struct for PostRenderer.
type PostRendererAssertion struct {
	Kustomize KustomizeAssertion
}

// IsAssertable marks PostRendererAssertion as an Assertable.
func (_ PostRendererAssertion) IsAssertable() {}

// ResourceInventoryAssertion is the assertion struct for ResourceInventory.
type ResourceInventoryAssertion struct {
	Entries assert.Opt[[]ResourceRefAssertion]
}

// IsAssertable marks ResourceInventoryAssertion as an Assertable.
func (_ ResourceInventoryAssertion) IsAssertable() {}

// ResourceRefAssertion is the assertion struct for ResourceRef.
type ResourceRefAssertion struct {
	ID      assert.Opt[string]
	Version assert.Opt[string]
}

// IsAssertable marks ResourceRefAssertion as an Assertable.
func (_ ResourceRefAssertion) IsAssertable() {}

// RollbackAssertion is the assertion struct for Rollback.
type RollbackAssertion struct {
	Timeout            assert.Opt[*v1.Duration]
	DisableWait        assert.Opt[bool]
	DisableWaitForJobs assert.Opt[bool]
	DisableHooks       assert.Opt[bool]
	Recreate           assert.Opt[bool]
	Force              assert.Opt[bool]
	CleanupOnFail      assert.Opt[bool]
	ServerSideApply    assert.Opt[v2.ServerSideApplyMode]
}

// IsAssertable marks RollbackAssertion as an Assertable.
func (_ RollbackAssertion) IsAssertable() {}

// SnapshotAssertion is the assertion struct for Snapshot.
type SnapshotAssertion struct {
	APIVersion    assert.Opt[string]
	Digest        assert.Opt[string]
	Name          assert.Opt[string]
	Namespace     assert.Opt[string]
	Version       assert.Opt[int]
	Status        assert.Opt[string]
	Action        assert.Opt[v2.ReleaseAction]
	ChartName     assert.Opt[string]
	ChartVersion  assert.Opt[string]
	AppVersion    assert.Opt[string]
	ConfigDigest  assert.Opt[string]
	FirstDeployed assert.Opt[v1.Time]
	LastDeployed  assert.Opt[v1.Time]
	Deleted       assert.Opt[v1.Time]
	TestHooks     assert.Opt[*map[string]*v2.TestHookStatus]
	OCIDigest     assert.Opt[string]
}

// IsAssertable marks SnapshotAssertion as an Assertable.
func (_ SnapshotAssertion) IsAssertable() {}

// TestAssertion is the assertion struct for Test.
type TestAssertion struct {
	Enable         assert.Opt[bool]
	Timeout        assert.Opt[*v1.Duration]
	IgnoreFailures assert.Opt[bool]
	Filters        assert.Opt[*[]v2.Filter]
}

// IsAssertable marks TestAssertion as an Assertable.
func (_ TestAssertion) IsAssertable() {}

// UninstallAssertion is the assertion struct for Uninstall.
type UninstallAssertion struct {
	Timeout             assert.Opt[*v1.Duration]
	DisableHooks        assert.Opt[bool]
	KeepHistory         assert.Opt[bool]
	DisableWait         assert.Opt[bool]
	DeletionPropagation assert.Opt[*string]
}

// IsAssertable marks UninstallAssertion as an Assertable.
func (_ UninstallAssertion) IsAssertable() {}

// UpgradeAssertion is the assertion struct for Upgrade.
type UpgradeAssertion struct {
	Timeout                  assert.Opt[*v1.Duration]
	Strategy                 UpgradeStrategyAssertion
	Remediation              UpgradeRemediationAssertion
	DisableTakeOwnership     assert.Opt[bool]
	DisableWait              assert.Opt[bool]
	DisableWaitForJobs       assert.Opt[bool]
	DisableHooks             assert.Opt[bool]
	DisableOpenAPIValidation assert.Opt[bool]
	DisableSchemaValidation  assert.Opt[bool]
	Force                    assert.Opt[bool]
	PreserveValues           assert.Opt[bool]
	CleanupOnFail            assert.Opt[bool]
	CRDs                     assert.Opt[v2.CRDsPolicy]
	ServerSideApply          assert.Opt[v2.ServerSideApplyMode]
}

// IsAssertable marks UpgradeAssertion as an Assertable.
func (_ UpgradeAssertion) IsAssertable() {}

// UpgradeRemediationAssertion is the assertion struct for UpgradeRemediation.
type UpgradeRemediationAssertion struct {
	Retries              assert.Opt[int]
	IgnoreTestFailures   assert.Opt[*bool]
	RemediateLastFailure assert.Opt[*bool]
	Strategy             assert.Opt[*v2.RemediationStrategy]
}

// IsAssertable marks UpgradeRemediationAssertion as an Assertable.
func (_ UpgradeRemediationAssertion) IsAssertable() {}

// UpgradeStrategyAssertion is the assertion struct for UpgradeStrategy.
type UpgradeStrategyAssertion struct {
	Name          assert.Opt[string]
	RetryInterval assert.Opt[*v1.Duration]
}

// IsAssertable marks UpgradeStrategyAssertion as an Assertable.
func (_ UpgradeStrategyAssertion) IsAssertable() {}

// WaitStrategyAssertion is the assertion struct for WaitStrategy.
type WaitStrategyAssertion struct {
	Name assert.Opt[v2.WaitStrategyName]
}

// IsAssertable marks WaitStrategyAssertion as an Assertable.
func (_ WaitStrategyAssertion) IsAssertable() {}
