// Code generated by assertgen. DO NOT EDIT.

package v1

import (
	acl "github.com/fluxcd/pkg/apis/acl"
	meta "github.com/fluxcd/pkg/apis/meta"
	v11 "github.com/fluxcd/source-controller/api/v1"
	assert "github.com/mridang/wilhelm/assert"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BucketAssertion is the assertion struct for Bucket.
type BucketAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       BucketSpecAssertion
	Status     assert.Opt[v11.BucketStatus]
}

// IsAssertable marks BucketAssertion as an Assertable.
func (_ BucketAssertion) IsAssertable() {}

// BucketSTSSpecAssertion is the assertion struct for BucketSTSSpec.
type BucketSTSSpecAssertion struct {
	Provider      assert.Opt[string]
	Endpoint      assert.Opt[string]
	SecretRef     assert.Opt[*meta.LocalObjectReference]
	CertSecretRef assert.Opt[*meta.LocalObjectReference]
}

// IsAssertable marks BucketSTSSpecAssertion as an Assertable.
func (_ BucketSTSSpecAssertion) IsAssertable() {}

// BucketSpecAssertion is the assertion struct for BucketSpec.
type BucketSpecAssertion struct {
	Provider           assert.Opt[string]
	BucketName         assert.Opt[string]
	Endpoint           assert.Opt[string]
	STS                BucketSTSSpecAssertion
	Insecure           assert.Opt[bool]
	Region             assert.Opt[string]
	Prefix             assert.Opt[string]
	SecretRef          assert.Opt[*meta.LocalObjectReference]
	ServiceAccountName assert.Opt[string]
	CertSecretRef      assert.Opt[*meta.LocalObjectReference]
	ProxySecretRef     assert.Opt[*meta.LocalObjectReference]
	Interval           assert.Opt[v1.Duration]
	Timeout            assert.Opt[*v1.Duration]
	Ignore             assert.Opt[*string]
	Suspend            assert.Opt[bool]
}

// IsAssertable marks BucketSpecAssertion as an Assertable.
func (_ BucketSpecAssertion) IsAssertable() {}

// ExternalArtifactAssertion is the assertion struct for ExternalArtifact.
type ExternalArtifactAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       ExternalArtifactSpecAssertion
	Status     assert.Opt[v11.ExternalArtifactStatus]
}

// IsAssertable marks ExternalArtifactAssertion as an Assertable.
func (_ ExternalArtifactAssertion) IsAssertable() {}

// ExternalArtifactSpecAssertion is the assertion struct for ExternalArtifactSpec.
type ExternalArtifactSpecAssertion struct {
	SourceRef assert.Opt[*meta.NamespacedObjectKindReference]
}

// IsAssertable marks ExternalArtifactSpecAssertion as an Assertable.
func (_ ExternalArtifactSpecAssertion) IsAssertable() {}

// GitRepositoryAssertion is the assertion struct for GitRepository.
type GitRepositoryAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       GitRepositorySpecAssertion
	Status     assert.Opt[v11.GitRepositoryStatus]
}

// IsAssertable marks GitRepositoryAssertion as an Assertable.
func (_ GitRepositoryAssertion) IsAssertable() {}

// GitRepositoryIncludeAssertion is the assertion struct for GitRepositoryInclude.
type GitRepositoryIncludeAssertion struct {
	GitRepositoryRef assert.Opt[meta.LocalObjectReference]
	FromPath         assert.Opt[string]
	ToPath           assert.Opt[string]
}

// IsAssertable marks GitRepositoryIncludeAssertion as an Assertable.
func (_ GitRepositoryIncludeAssertion) IsAssertable() {}

// GitRepositoryRefAssertion is the assertion struct for GitRepositoryRef.
type GitRepositoryRefAssertion struct {
	Branch assert.Opt[string]
	Tag    assert.Opt[string]
	SemVer assert.Opt[string]
	Name   assert.Opt[string]
	Commit assert.Opt[string]
}

// IsAssertable marks GitRepositoryRefAssertion as an Assertable.
func (_ GitRepositoryRefAssertion) IsAssertable() {}

// GitRepositorySpecAssertion is the assertion struct for GitRepositorySpec.
type GitRepositorySpecAssertion struct {
	URL                assert.Opt[string]
	SecretRef          assert.Opt[*meta.LocalObjectReference]
	Provider           assert.Opt[string]
	ServiceAccountName assert.Opt[string]
	Interval           assert.Opt[v1.Duration]
	Timeout            assert.Opt[*v1.Duration]
	Reference          GitRepositoryRefAssertion
	Verification       GitRepositoryVerificationAssertion
	ProxySecretRef     assert.Opt[*meta.LocalObjectReference]
	Ignore             assert.Opt[*string]
	Suspend            assert.Opt[bool]
	RecurseSubmodules  assert.Opt[bool]
	Include            assert.Opt[[]GitRepositoryIncludeAssertion]
	SparseCheckout     assert.Opt[[]string]
}

// IsAssertable marks GitRepositorySpecAssertion as an Assertable.
func (_ GitRepositorySpecAssertion) IsAssertable() {}

// GitRepositoryVerificationAssertion is the assertion struct for GitRepositoryVerification.
type GitRepositoryVerificationAssertion struct {
	Mode      assert.Opt[v11.GitVerificationMode]
	SecretRef assert.Opt[meta.LocalObjectReference]
}

// IsAssertable marks GitRepositoryVerificationAssertion as an Assertable.
func (_ GitRepositoryVerificationAssertion) IsAssertable() {}

// GroupVersionAssertion is the assertion struct for GroupVersion.
type GroupVersionAssertion struct {
	Group   assert.Opt[string]
	Version assert.Opt[string]
}

// IsAssertable marks GroupVersionAssertion as an Assertable.
func (_ GroupVersionAssertion) IsAssertable() {}

// HelmChartAssertion is the assertion struct for HelmChart.
type HelmChartAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       HelmChartSpecAssertion
	Status     assert.Opt[v11.HelmChartStatus]
}

// IsAssertable marks HelmChartAssertion as an Assertable.
func (_ HelmChartAssertion) IsAssertable() {}

// HelmChartSpecAssertion is the assertion struct for HelmChartSpec.
type HelmChartSpecAssertion struct {
	Chart                    assert.Opt[string]
	Version                  assert.Opt[string]
	SourceRef                LocalHelmChartSourceReferenceAssertion
	Interval                 assert.Opt[v1.Duration]
	ReconcileStrategy        assert.Opt[string]
	ValuesFiles              assert.Opt[[]string]
	IgnoreMissingValuesFiles assert.Opt[bool]
	Suspend                  assert.Opt[bool]
	Verify                   OCIRepositoryVerificationAssertion
}

// IsAssertable marks HelmChartSpecAssertion as an Assertable.
func (_ HelmChartSpecAssertion) IsAssertable() {}

// HelmRepositoryAssertion is the assertion struct for HelmRepository.
type HelmRepositoryAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       HelmRepositorySpecAssertion
	Status     assert.Opt[v11.HelmRepositoryStatus]
}

// IsAssertable marks HelmRepositoryAssertion as an Assertable.
func (_ HelmRepositoryAssertion) IsAssertable() {}

// HelmRepositorySpecAssertion is the assertion struct for HelmRepositorySpec.
type HelmRepositorySpecAssertion struct {
	URL             assert.Opt[string]
	SecretRef       assert.Opt[*meta.LocalObjectReference]
	CertSecretRef   assert.Opt[*meta.LocalObjectReference]
	PassCredentials assert.Opt[bool]
	Interval        assert.Opt[v1.Duration]
	Insecure        assert.Opt[bool]
	Timeout         assert.Opt[*v1.Duration]
	Suspend         assert.Opt[bool]
	AccessFrom      assert.Opt[*acl.AccessFrom]
	Type            assert.Opt[string]
	Provider        assert.Opt[string]
}

// IsAssertable marks HelmRepositorySpecAssertion as an Assertable.
func (_ HelmRepositorySpecAssertion) IsAssertable() {}

// LocalHelmChartSourceReferenceAssertion is the assertion struct for LocalHelmChartSourceReference.
type LocalHelmChartSourceReferenceAssertion struct {
	APIVersion assert.Opt[string]
	Kind       assert.Opt[string]
	Name       assert.Opt[string]
}

// IsAssertable marks LocalHelmChartSourceReferenceAssertion as an Assertable.
func (_ LocalHelmChartSourceReferenceAssertion) IsAssertable() {}

// OCILayerSelectorAssertion is the assertion struct for OCILayerSelector.
type OCILayerSelectorAssertion struct {
	MediaType assert.Opt[string]
	Operation assert.Opt[string]
}

// IsAssertable marks OCILayerSelectorAssertion as an Assertable.
func (_ OCILayerSelectorAssertion) IsAssertable() {}

// OCIRepositoryAssertion is the assertion struct for OCIRepository.
type OCIRepositoryAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       OCIRepositorySpecAssertion
	Status     assert.Opt[v11.OCIRepositoryStatus]
}

// IsAssertable marks OCIRepositoryAssertion as an Assertable.
func (_ OCIRepositoryAssertion) IsAssertable() {}

// OCIRepositoryRefAssertion is the assertion struct for OCIRepositoryRef.
type OCIRepositoryRefAssertion struct {
	Digest       assert.Opt[string]
	SemVer       assert.Opt[string]
	SemverFilter assert.Opt[string]
	Tag          assert.Opt[string]
}

// IsAssertable marks OCIRepositoryRefAssertion as an Assertable.
func (_ OCIRepositoryRefAssertion) IsAssertable() {}

// OCIRepositorySpecAssertion is the assertion struct for OCIRepositorySpec.
type OCIRepositorySpecAssertion struct {
	URL                assert.Opt[string]
	Reference          OCIRepositoryRefAssertion
	LayerSelector      OCILayerSelectorAssertion
	Provider           assert.Opt[string]
	SecretRef          assert.Opt[*meta.LocalObjectReference]
	Verify             OCIRepositoryVerificationAssertion
	ServiceAccountName assert.Opt[string]
	CertSecretRef      assert.Opt[*meta.LocalObjectReference]
	ProxySecretRef     assert.Opt[*meta.LocalObjectReference]
	Interval           assert.Opt[v1.Duration]
	Timeout            assert.Opt[*v1.Duration]
	Ignore             assert.Opt[*string]
	Insecure           assert.Opt[bool]
	Suspend            assert.Opt[bool]
}

// IsAssertable marks OCIRepositorySpecAssertion as an Assertable.
func (_ OCIRepositorySpecAssertion) IsAssertable() {}

// OCIRepositoryVerificationAssertion is the assertion struct for OCIRepositoryVerification.
type OCIRepositoryVerificationAssertion struct {
	Provider          assert.Opt[string]
	SecretRef         assert.Opt[*meta.LocalObjectReference]
	MatchOIDCIdentity assert.Opt[[]OIDCIdentityMatchAssertion]
}

// IsAssertable marks OCIRepositoryVerificationAssertion as an Assertable.
func (_ OCIRepositoryVerificationAssertion) IsAssertable() {}

// OIDCIdentityMatchAssertion is the assertion struct for OIDCIdentityMatch.
type OIDCIdentityMatchAssertion struct {
	Issuer  assert.Opt[string]
	Subject assert.Opt[string]
}

// IsAssertable marks OIDCIdentityMatchAssertion as an Assertable.
func (_ OIDCIdentityMatchAssertion) IsAssertable() {}
