// Code generated by assertgen. DO NOT EDIT.

package v1alpha1

import (
	assert "github.com/mridang/wilhelm/assert"
	dynamic "github.com/traefik/traefik/v3/pkg/config/dynamic"
	tls "github.com/traefik/traefik/v3/pkg/tls"
	types "github.com/traefik/traefik/v3/pkg/types"
	v11 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// BasicAuthAssertion is the assertion struct for BasicAuth.
type BasicAuthAssertion struct {
	Secret       assert.Opt[string]
	Realm        assert.Opt[string]
	RemoveHeader assert.Opt[bool]
	HeaderField  assert.Opt[string]
}

// IsAssertable marks BasicAuthAssertion as an Assertable.
func (_ BasicAuthAssertion) IsAssertable() {}

// CertificateAssertion is the assertion struct for Certificate.
type CertificateAssertion struct {
	SecretName assert.Opt[string]
}

// IsAssertable marks CertificateAssertion as an Assertable.
func (_ CertificateAssertion) IsAssertable() {}

// ChainAssertion is the assertion struct for Chain.
type ChainAssertion struct {
	Middlewares assert.Opt[[]MiddlewareRefAssertion]
}

// IsAssertable marks ChainAssertion as an Assertable.
func (_ ChainAssertion) IsAssertable() {}

// CircuitBreakerAssertion is the assertion struct for CircuitBreaker.
type CircuitBreakerAssertion struct {
	Expression       assert.Opt[string]
	CheckPeriod      assert.Opt[*intstr.IntOrString]
	FallbackDuration assert.Opt[*intstr.IntOrString]
	RecoveryDuration assert.Opt[*intstr.IntOrString]
	ResponseCode     assert.Opt[int]
}

// IsAssertable marks CircuitBreakerAssertion as an Assertable.
func (_ CircuitBreakerAssertion) IsAssertable() {}

// ClientAuthAssertion is the assertion struct for ClientAuth.
type ClientAuthAssertion struct {
	SecretNames    assert.Opt[[]string]
	ClientAuthType assert.Opt[string]
}

// IsAssertable marks ClientAuthAssertion as an Assertable.
func (_ ClientAuthAssertion) IsAssertable() {}

// ClientTLSAssertion is the assertion struct for ClientTLS.
type ClientTLSAssertion struct {
	CASecret           assert.Opt[string]
	CertSecret         assert.Opt[string]
	InsecureSkipVerify assert.Opt[bool]
	CAOptional         assert.Opt[*bool]
}

// IsAssertable marks ClientTLSAssertion as an Assertable.
func (_ ClientTLSAssertion) IsAssertable() {}

// CompressAssertion is the assertion struct for Compress.
type CompressAssertion struct {
	ExcludedContentTypes assert.Opt[[]string]
	IncludedContentTypes assert.Opt[[]string]
	MinResponseBodyBytes assert.Opt[*int]
	Encodings            assert.Opt[[]string]
	DefaultEncoding      assert.Opt[*string]
}

// IsAssertable marks CompressAssertion as an Assertable.
func (_ CompressAssertion) IsAssertable() {}

// DigestAuthAssertion is the assertion struct for DigestAuth.
type DigestAuthAssertion struct {
	Secret       assert.Opt[string]
	RemoveHeader assert.Opt[bool]
	Realm        assert.Opt[string]
	HeaderField  assert.Opt[string]
}

// IsAssertable marks DigestAuthAssertion as an Assertable.
func (_ DigestAuthAssertion) IsAssertable() {}

// ErrorPageAssertion is the assertion struct for ErrorPage.
type ErrorPageAssertion struct {
	Status  assert.Opt[[]string]
	Service ServiceAssertion
	Query   assert.Opt[string]
}

// IsAssertable marks ErrorPageAssertion as an Assertable.
func (_ ErrorPageAssertion) IsAssertable() {}

// ForwardAuthAssertion is the assertion struct for ForwardAuth.
type ForwardAuthAssertion struct {
	Address                  assert.Opt[string]
	TrustForwardHeader       assert.Opt[bool]
	AuthResponseHeaders      assert.Opt[[]string]
	AuthResponseHeadersRegex assert.Opt[string]
	AuthRequestHeaders       assert.Opt[[]string]
	TLS                      ClientTLSAssertion
	AddAuthCookiesToResponse assert.Opt[[]string]
}

// IsAssertable marks ForwardAuthAssertion as an Assertable.
func (_ ForwardAuthAssertion) IsAssertable() {}

// ForwardingTimeoutsAssertion is the assertion struct for ForwardingTimeouts.
type ForwardingTimeoutsAssertion struct {
	DialTimeout           assert.Opt[*intstr.IntOrString]
	ResponseHeaderTimeout assert.Opt[*intstr.IntOrString]
	IdleConnTimeout       assert.Opt[*intstr.IntOrString]
	ReadIdleTimeout       assert.Opt[*intstr.IntOrString]
	PingTimeout           assert.Opt[*intstr.IntOrString]
}

// IsAssertable marks ForwardingTimeoutsAssertion as an Assertable.
func (_ ForwardingTimeoutsAssertion) IsAssertable() {}

// IngressRouteAssertion is the assertion struct for IngressRoute.
type IngressRouteAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       IngressRouteSpecAssertion
}

// IsAssertable marks IngressRouteAssertion as an Assertable.
func (_ IngressRouteAssertion) IsAssertable() {}

// IngressRouteSpecAssertion is the assertion struct for IngressRouteSpec.
type IngressRouteSpecAssertion struct {
	Routes      assert.Opt[[]RouteAssertion]
	EntryPoints assert.Opt[[]string]
	TLS         TLSAssertion
}

// IsAssertable marks IngressRouteSpecAssertion as an Assertable.
func (_ IngressRouteSpecAssertion) IsAssertable() {}

// IngressRouteTCPAssertion is the assertion struct for IngressRouteTCP.
type IngressRouteTCPAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       IngressRouteTCPSpecAssertion
}

// IsAssertable marks IngressRouteTCPAssertion as an Assertable.
func (_ IngressRouteTCPAssertion) IsAssertable() {}

// IngressRouteTCPSpecAssertion is the assertion struct for IngressRouteTCPSpec.
type IngressRouteTCPSpecAssertion struct {
	Routes      assert.Opt[[]RouteTCPAssertion]
	EntryPoints assert.Opt[[]string]
	TLS         TLSTCPAssertion
}

// IsAssertable marks IngressRouteTCPSpecAssertion as an Assertable.
func (_ IngressRouteTCPSpecAssertion) IsAssertable() {}

// IngressRouteUDPAssertion is the assertion struct for IngressRouteUDP.
type IngressRouteUDPAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       IngressRouteUDPSpecAssertion
}

// IsAssertable marks IngressRouteUDPAssertion as an Assertable.
func (_ IngressRouteUDPAssertion) IsAssertable() {}

// IngressRouteUDPSpecAssertion is the assertion struct for IngressRouteUDPSpec.
type IngressRouteUDPSpecAssertion struct {
	Routes      assert.Opt[[]RouteUDPAssertion]
	EntryPoints assert.Opt[[]string]
}

// IsAssertable marks IngressRouteUDPSpecAssertion as an Assertable.
func (_ IngressRouteUDPSpecAssertion) IsAssertable() {}

// LoadBalancerSpecAssertion is the assertion struct for LoadBalancerSpec.
type LoadBalancerSpecAssertion struct {
	Name               assert.Opt[string]
	Kind               assert.Opt[string]
	Namespace          assert.Opt[string]
	Sticky             assert.Opt[*dynamic.Sticky]
	Port               assert.Opt[intstr.IntOrString]
	Scheme             assert.Opt[string]
	Strategy           assert.Opt[string]
	PassHostHeader     assert.Opt[*bool]
	ResponseForwarding ResponseForwardingAssertion
	ServersTransport   assert.Opt[string]
	Weight             assert.Opt[*int]
	NativeLB           assert.Opt[*bool]
	NodePortLB         assert.Opt[bool]
	HealthCheck        ServerHealthCheckAssertion
}

// IsAssertable marks LoadBalancerSpecAssertion as an Assertable.
func (_ LoadBalancerSpecAssertion) IsAssertable() {}

// MiddlewareAssertion is the assertion struct for Middleware.
type MiddlewareAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       MiddlewareSpecAssertion
}

// IsAssertable marks MiddlewareAssertion as an Assertable.
func (_ MiddlewareAssertion) IsAssertable() {}

// MiddlewareRefAssertion is the assertion struct for MiddlewareRef.
type MiddlewareRefAssertion struct {
	Name      assert.Opt[string]
	Namespace assert.Opt[string]
}

// IsAssertable marks MiddlewareRefAssertion as an Assertable.
func (_ MiddlewareRefAssertion) IsAssertable() {}

// MiddlewareSpecAssertion is the assertion struct for MiddlewareSpec.
type MiddlewareSpecAssertion struct {
	AddPrefix         assert.Opt[*dynamic.AddPrefix]
	StripPrefix       assert.Opt[*dynamic.StripPrefix]
	StripPrefixRegex  assert.Opt[*dynamic.StripPrefixRegex]
	ReplacePath       assert.Opt[*dynamic.ReplacePath]
	ReplacePathRegex  assert.Opt[*dynamic.ReplacePathRegex]
	Chain             ChainAssertion
	IPWhiteList       assert.Opt[*dynamic.IPWhiteList]
	IPAllowList       assert.Opt[*dynamic.IPAllowList]
	Headers           assert.Opt[*dynamic.Headers]
	Errors            ErrorPageAssertion
	RateLimit         RateLimitAssertion
	RedirectRegex     assert.Opt[*dynamic.RedirectRegex]
	RedirectScheme    assert.Opt[*dynamic.RedirectScheme]
	BasicAuth         BasicAuthAssertion
	DigestAuth        DigestAuthAssertion
	ForwardAuth       ForwardAuthAssertion
	InFlightReq       assert.Opt[*dynamic.InFlightReq]
	Buffering         assert.Opt[*dynamic.Buffering]
	CircuitBreaker    CircuitBreakerAssertion
	Compress          CompressAssertion
	PassTLSClientCert assert.Opt[*dynamic.PassTLSClientCert]
	Retry             RetryAssertion
	ContentType       assert.Opt[*dynamic.ContentType]
	GrpcWeb           assert.Opt[*dynamic.GrpcWeb]
	Plugin            assert.Opt[map[string]v11.JSON]
}

// IsAssertable marks MiddlewareSpecAssertion as an Assertable.
func (_ MiddlewareSpecAssertion) IsAssertable() {}

// MiddlewareTCPAssertion is the assertion struct for MiddlewareTCP.
type MiddlewareTCPAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       MiddlewareTCPSpecAssertion
}

// IsAssertable marks MiddlewareTCPAssertion as an Assertable.
func (_ MiddlewareTCPAssertion) IsAssertable() {}

// MiddlewareTCPSpecAssertion is the assertion struct for MiddlewareTCPSpec.
type MiddlewareTCPSpecAssertion struct {
	InFlightConn assert.Opt[*dynamic.TCPInFlightConn]
	IPWhiteList  assert.Opt[*dynamic.TCPIPWhiteList]
	IPAllowList  assert.Opt[*dynamic.TCPIPAllowList]
}

// IsAssertable marks MiddlewareTCPSpecAssertion as an Assertable.
func (_ MiddlewareTCPSpecAssertion) IsAssertable() {}

// MirrorServiceAssertion is the assertion struct for MirrorService.
type MirrorServiceAssertion struct {
	LoadBalancerSpec LoadBalancerSpecAssertion
	Percent          assert.Opt[int]
}

// IsAssertable marks MirrorServiceAssertion as an Assertable.
func (_ MirrorServiceAssertion) IsAssertable() {}

// MirroringAssertion is the assertion struct for Mirroring.
type MirroringAssertion struct {
	LoadBalancerSpec LoadBalancerSpecAssertion
	MirrorBody       assert.Opt[*bool]
	MaxBodySize      assert.Opt[*int64]
	Mirrors          assert.Opt[[]MirrorServiceAssertion]
}

// IsAssertable marks MirroringAssertion as an Assertable.
func (_ MirroringAssertion) IsAssertable() {}

// ObjectReferenceAssertion is the assertion struct for ObjectReference.
type ObjectReferenceAssertion struct {
	Name      assert.Opt[string]
	Namespace assert.Opt[string]
}

// IsAssertable marks ObjectReferenceAssertion as an Assertable.
func (_ ObjectReferenceAssertion) IsAssertable() {}

// RateLimitAssertion is the assertion struct for RateLimit.
type RateLimitAssertion struct {
	Average         assert.Opt[*int64]
	Period          assert.Opt[*intstr.IntOrString]
	Burst           assert.Opt[*int64]
	SourceCriterion assert.Opt[*dynamic.SourceCriterion]
}

// IsAssertable marks RateLimitAssertion as an Assertable.
func (_ RateLimitAssertion) IsAssertable() {}

// ResponseForwardingAssertion is the assertion struct for ResponseForwarding.
type ResponseForwardingAssertion struct {
	FlushInterval assert.Opt[string]
}

// IsAssertable marks ResponseForwardingAssertion as an Assertable.
func (_ ResponseForwardingAssertion) IsAssertable() {}

// RetryAssertion is the assertion struct for Retry.
type RetryAssertion struct {
	Attempts        assert.Opt[int]
	InitialInterval assert.Opt[intstr.IntOrString]
}

// IsAssertable marks RetryAssertion as an Assertable.
func (_ RetryAssertion) IsAssertable() {}

// RouteAssertion is the assertion struct for Route.
type RouteAssertion struct {
	Match       assert.Opt[string]
	Kind        assert.Opt[string]
	Priority    assert.Opt[int]
	Syntax      assert.Opt[string]
	Services    assert.Opt[[]ServiceAssertion]
	Middlewares assert.Opt[[]MiddlewareRefAssertion]
}

// IsAssertable marks RouteAssertion as an Assertable.
func (_ RouteAssertion) IsAssertable() {}

// RouteTCPAssertion is the assertion struct for RouteTCP.
type RouteTCPAssertion struct {
	Match       assert.Opt[string]
	Priority    assert.Opt[int]
	Syntax      assert.Opt[string]
	Services    assert.Opt[[]ServiceTCPAssertion]
	Middlewares assert.Opt[[]ObjectReferenceAssertion]
}

// IsAssertable marks RouteTCPAssertion as an Assertable.
func (_ RouteTCPAssertion) IsAssertable() {}

// RouteUDPAssertion is the assertion struct for RouteUDP.
type RouteUDPAssertion struct {
	Services assert.Opt[[]ServiceUDPAssertion]
}

// IsAssertable marks RouteUDPAssertion as an Assertable.
func (_ RouteUDPAssertion) IsAssertable() {}

// SchemeGroupVersionAssertion is the assertion struct for GroupVersion.
type SchemeGroupVersionAssertion struct {
	Group   assert.Opt[string]
	Version assert.Opt[string]
}

// IsAssertable marks SchemeGroupVersionAssertion as an Assertable.
func (_ SchemeGroupVersionAssertion) IsAssertable() {}

// ServerHealthCheckAssertion is the assertion struct for ServerHealthCheck.
type ServerHealthCheckAssertion struct {
	Scheme          assert.Opt[string]
	Mode            assert.Opt[string]
	Path            assert.Opt[string]
	Method          assert.Opt[string]
	Status          assert.Opt[int]
	Port            assert.Opt[int]
	Interval        assert.Opt[*intstr.IntOrString]
	Timeout         assert.Opt[*intstr.IntOrString]
	Hostname        assert.Opt[string]
	FollowRedirects assert.Opt[*bool]
	Headers         assert.Opt[map[string]string]
}

// IsAssertable marks ServerHealthCheckAssertion as an Assertable.
func (_ ServerHealthCheckAssertion) IsAssertable() {}

// ServersTransportAssertion is the assertion struct for ServersTransport.
type ServersTransportAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       ServersTransportSpecAssertion
}

// IsAssertable marks ServersTransportAssertion as an Assertable.
func (_ ServersTransportAssertion) IsAssertable() {}

// ServersTransportSpecAssertion is the assertion struct for ServersTransportSpec.
type ServersTransportSpecAssertion struct {
	ServerName          assert.Opt[string]
	InsecureSkipVerify  assert.Opt[bool]
	RootCAsSecrets      assert.Opt[[]string]
	CertificatesSecrets assert.Opt[[]string]
	MaxIdleConnsPerHost assert.Opt[int]
	ForwardingTimeouts  ForwardingTimeoutsAssertion
	DisableHTTP2        assert.Opt[bool]
	PeerCertURI         assert.Opt[string]
	Spiffe              assert.Opt[*dynamic.Spiffe]
}

// IsAssertable marks ServersTransportSpecAssertion as an Assertable.
func (_ ServersTransportSpecAssertion) IsAssertable() {}

// ServersTransportTCPAssertion is the assertion struct for ServersTransportTCP.
type ServersTransportTCPAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       ServersTransportTCPSpecAssertion
}

// IsAssertable marks ServersTransportTCPAssertion as an Assertable.
func (_ ServersTransportTCPAssertion) IsAssertable() {}

// ServersTransportTCPSpecAssertion is the assertion struct for ServersTransportTCPSpec.
type ServersTransportTCPSpecAssertion struct {
	DialTimeout      assert.Opt[*intstr.IntOrString]
	DialKeepAlive    assert.Opt[*intstr.IntOrString]
	TerminationDelay assert.Opt[*intstr.IntOrString]
	TLS              TLSClientConfigAssertion
}

// IsAssertable marks ServersTransportTCPSpecAssertion as an Assertable.
func (_ ServersTransportTCPSpecAssertion) IsAssertable() {}

// ServiceAssertion is the assertion struct for Service.
type ServiceAssertion struct {
	LoadBalancerSpec LoadBalancerSpecAssertion
}

// IsAssertable marks ServiceAssertion as an Assertable.
func (_ ServiceAssertion) IsAssertable() {}

// ServiceTCPAssertion is the assertion struct for ServiceTCP.
type ServiceTCPAssertion struct {
	Name             assert.Opt[string]
	Namespace        assert.Opt[string]
	Port             assert.Opt[intstr.IntOrString]
	Weight           assert.Opt[*int]
	TerminationDelay assert.Opt[*int]
	ProxyProtocol    assert.Opt[*dynamic.ProxyProtocol]
	ServersTransport assert.Opt[string]
	TLS              assert.Opt[bool]
	NativeLB         assert.Opt[*bool]
	NodePortLB       assert.Opt[bool]
}

// IsAssertable marks ServiceTCPAssertion as an Assertable.
func (_ ServiceTCPAssertion) IsAssertable() {}

// ServiceUDPAssertion is the assertion struct for ServiceUDP.
type ServiceUDPAssertion struct {
	Name       assert.Opt[string]
	Namespace  assert.Opt[string]
	Port       assert.Opt[intstr.IntOrString]
	Weight     assert.Opt[*int]
	NativeLB   assert.Opt[*bool]
	NodePortLB assert.Opt[bool]
}

// IsAssertable marks ServiceUDPAssertion as an Assertable.
func (_ ServiceUDPAssertion) IsAssertable() {}

// TLSAssertion is the assertion struct for TLS.
type TLSAssertion struct {
	SecretName   assert.Opt[string]
	Options      TLSOptionRefAssertion
	Store        TLSStoreRefAssertion
	CertResolver assert.Opt[string]
	Domains      assert.Opt[[]types.Domain]
}

// IsAssertable marks TLSAssertion as an Assertable.
func (_ TLSAssertion) IsAssertable() {}

// TLSClientConfigAssertion is the assertion struct for TLSClientConfig.
type TLSClientConfigAssertion struct {
	ServerName          assert.Opt[string]
	InsecureSkipVerify  assert.Opt[bool]
	RootCAsSecrets      assert.Opt[[]string]
	CertificatesSecrets assert.Opt[[]string]
	PeerCertURI         assert.Opt[string]
	Spiffe              assert.Opt[*dynamic.Spiffe]
}

// IsAssertable marks TLSClientConfigAssertion as an Assertable.
func (_ TLSClientConfigAssertion) IsAssertable() {}

// TLSOptionAssertion is the assertion struct for TLSOption.
type TLSOptionAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       TLSOptionSpecAssertion
}

// IsAssertable marks TLSOptionAssertion as an Assertable.
func (_ TLSOptionAssertion) IsAssertable() {}

// TLSOptionRefAssertion is the assertion struct for TLSOptionRef.
type TLSOptionRefAssertion struct {
	Name      assert.Opt[string]
	Namespace assert.Opt[string]
}

// IsAssertable marks TLSOptionRefAssertion as an Assertable.
func (_ TLSOptionRefAssertion) IsAssertable() {}

// TLSOptionSpecAssertion is the assertion struct for TLSOptionSpec.
type TLSOptionSpecAssertion struct {
	MinVersion               assert.Opt[string]
	MaxVersion               assert.Opt[string]
	CipherSuites             assert.Opt[[]string]
	CurvePreferences         assert.Opt[[]string]
	ClientAuth               ClientAuthAssertion
	SniStrict                assert.Opt[bool]
	ALPNProtocols            assert.Opt[[]string]
	PreferServerCipherSuites assert.Opt[*bool]
}

// IsAssertable marks TLSOptionSpecAssertion as an Assertable.
func (_ TLSOptionSpecAssertion) IsAssertable() {}

// TLSStoreAssertion is the assertion struct for TLSStore.
type TLSStoreAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       TLSStoreSpecAssertion
}

// IsAssertable marks TLSStoreAssertion as an Assertable.
func (_ TLSStoreAssertion) IsAssertable() {}

// TLSStoreRefAssertion is the assertion struct for TLSStoreRef.
type TLSStoreRefAssertion struct {
	Name      assert.Opt[string]
	Namespace assert.Opt[string]
}

// IsAssertable marks TLSStoreRefAssertion as an Assertable.
func (_ TLSStoreRefAssertion) IsAssertable() {}

// TLSStoreSpecAssertion is the assertion struct for TLSStoreSpec.
type TLSStoreSpecAssertion struct {
	DefaultCertificate   CertificateAssertion
	DefaultGeneratedCert assert.Opt[*tls.GeneratedCert]
	Certificates         assert.Opt[[]CertificateAssertion]
}

// IsAssertable marks TLSStoreSpecAssertion as an Assertable.
func (_ TLSStoreSpecAssertion) IsAssertable() {}

// TLSTCPAssertion is the assertion struct for TLSTCP.
type TLSTCPAssertion struct {
	SecretName   assert.Opt[string]
	Passthrough  assert.Opt[bool]
	Options      ObjectReferenceAssertion
	Store        ObjectReferenceAssertion
	CertResolver assert.Opt[string]
	Domains      assert.Opt[[]types.Domain]
}

// IsAssertable marks TLSTCPAssertion as an Assertable.
func (_ TLSTCPAssertion) IsAssertable() {}

// TraefikServiceAssertion is the assertion struct for TraefikService.
type TraefikServiceAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       TraefikServiceSpecAssertion
}

// IsAssertable marks TraefikServiceAssertion as an Assertable.
func (_ TraefikServiceAssertion) IsAssertable() {}

// TraefikServiceSpecAssertion is the assertion struct for TraefikServiceSpec.
type TraefikServiceSpecAssertion struct {
	Weighted  WeightedRoundRobinAssertion
	Mirroring MirroringAssertion
}

// IsAssertable marks TraefikServiceSpecAssertion as an Assertable.
func (_ TraefikServiceSpecAssertion) IsAssertable() {}

// WeightedRoundRobinAssertion is the assertion struct for WeightedRoundRobin.
type WeightedRoundRobinAssertion struct {
	Services assert.Opt[[]ServiceAssertion]
	Sticky   assert.Opt[*dynamic.Sticky]
}

// IsAssertable marks WeightedRoundRobinAssertion as an Assertable.
func (_ WeightedRoundRobinAssertion) IsAssertable() {}
