// Code generated by envgen. DO NOT EDIT.

package v1alpha1

import (
	"fmt"
	assert "github.com/mridang/wilhelm/assert"
	v1alpha11 "github.com/mridang/wilhelm/assert/traefik/io/v1alpha1"
	env "github.com/mridang/wilhelm/env"
	require "github.com/stretchr/testify/require"
	v1alpha1 "github.com/traefik/traefik/v3/pkg/provider/kubernetes/crd/traefikio/v1alpha1"
	errors "k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	"testing"
)

// GetIngressRoute fetches a IngressRoute by name via the dynamic client, failing the test on error.
func GetIngressRoute(env *env.Env, t *testing.T, name string) *v1alpha1.IngressRoute {
	t.Helper()
	obj, err := GetIngressRouteE(env, t, name)
	require.NoError(t, err, "failed to get IngressRoute %s", name)
	return obj
}

// GetIngressRouteE fetches a IngressRoute by name via the dynamic client, returning the error for non-existence checks.
func GetIngressRouteE(env *env.Env, t *testing.T, name string) (*v1alpha1.IngressRoute, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "traefik.io",
		Resource: "ingressroutes",
		Version:  "v1alpha1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1alpha1.IngressRoute
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert IngressRoute from unstructured: %w", err)
	}
	return &out, nil
}

// AssertIngressRoute fetches a IngressRoute and runs a partial assertion against it.
func AssertIngressRoute(env *env.Env, t *testing.T, name string, asn v1alpha11.IngressRouteAssertion) {
	t.Helper()
	assert.Partial(t, GetIngressRoute(env, t, name), asn, name)
}

// GetIngressRouteTCP fetches a IngressRouteTCP by name via the dynamic client, failing the test on error.
func GetIngressRouteTCP(env *env.Env, t *testing.T, name string) *v1alpha1.IngressRouteTCP {
	t.Helper()
	obj, err := GetIngressRouteTCPE(env, t, name)
	require.NoError(t, err, "failed to get IngressRouteTCP %s", name)
	return obj
}

// GetIngressRouteTCPE fetches a IngressRouteTCP by name via the dynamic client, returning the error for non-existence checks.
func GetIngressRouteTCPE(env *env.Env, t *testing.T, name string) (*v1alpha1.IngressRouteTCP, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "traefik.io",
		Resource: "ingressroutetcps",
		Version:  "v1alpha1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1alpha1.IngressRouteTCP
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert IngressRouteTCP from unstructured: %w", err)
	}
	return &out, nil
}

// AssertIngressRouteTCP fetches a IngressRouteTCP and runs a partial assertion against it.
func AssertIngressRouteTCP(env *env.Env, t *testing.T, name string, asn v1alpha11.IngressRouteTCPAssertion) {
	t.Helper()
	assert.Partial(t, GetIngressRouteTCP(env, t, name), asn, name)
}

// GetIngressRouteUDP fetches a IngressRouteUDP by name via the dynamic client, failing the test on error.
func GetIngressRouteUDP(env *env.Env, t *testing.T, name string) *v1alpha1.IngressRouteUDP {
	t.Helper()
	obj, err := GetIngressRouteUDPE(env, t, name)
	require.NoError(t, err, "failed to get IngressRouteUDP %s", name)
	return obj
}

// GetIngressRouteUDPE fetches a IngressRouteUDP by name via the dynamic client, returning the error for non-existence checks.
func GetIngressRouteUDPE(env *env.Env, t *testing.T, name string) (*v1alpha1.IngressRouteUDP, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "traefik.io",
		Resource: "ingressrouteudps",
		Version:  "v1alpha1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1alpha1.IngressRouteUDP
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert IngressRouteUDP from unstructured: %w", err)
	}
	return &out, nil
}

// AssertIngressRouteUDP fetches a IngressRouteUDP and runs a partial assertion against it.
func AssertIngressRouteUDP(env *env.Env, t *testing.T, name string, asn v1alpha11.IngressRouteUDPAssertion) {
	t.Helper()
	assert.Partial(t, GetIngressRouteUDP(env, t, name), asn, name)
}

// GetMiddleware fetches a Middleware by name via the dynamic client, failing the test on error.
func GetMiddleware(env *env.Env, t *testing.T, name string) *v1alpha1.Middleware {
	t.Helper()
	obj, err := GetMiddlewareE(env, t, name)
	require.NoError(t, err, "failed to get Middleware %s", name)
	return obj
}

// GetMiddlewareE fetches a Middleware by name via the dynamic client, returning the error for non-existence checks.
func GetMiddlewareE(env *env.Env, t *testing.T, name string) (*v1alpha1.Middleware, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "traefik.io",
		Resource: "middlewares",
		Version:  "v1alpha1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1alpha1.Middleware
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert Middleware from unstructured: %w", err)
	}
	return &out, nil
}

// AssertMiddleware fetches a Middleware and runs a partial assertion against it.
func AssertMiddleware(env *env.Env, t *testing.T, name string, asn v1alpha11.MiddlewareAssertion) {
	t.Helper()
	assert.Partial(t, GetMiddleware(env, t, name), asn, name)
}

// GetMiddlewareTCP fetches a MiddlewareTCP by name via the dynamic client, failing the test on error.
func GetMiddlewareTCP(env *env.Env, t *testing.T, name string) *v1alpha1.MiddlewareTCP {
	t.Helper()
	obj, err := GetMiddlewareTCPE(env, t, name)
	require.NoError(t, err, "failed to get MiddlewareTCP %s", name)
	return obj
}

// GetMiddlewareTCPE fetches a MiddlewareTCP by name via the dynamic client, returning the error for non-existence checks.
func GetMiddlewareTCPE(env *env.Env, t *testing.T, name string) (*v1alpha1.MiddlewareTCP, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "traefik.io",
		Resource: "middlewaretcps",
		Version:  "v1alpha1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1alpha1.MiddlewareTCP
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert MiddlewareTCP from unstructured: %w", err)
	}
	return &out, nil
}

// AssertMiddlewareTCP fetches a MiddlewareTCP and runs a partial assertion against it.
func AssertMiddlewareTCP(env *env.Env, t *testing.T, name string, asn v1alpha11.MiddlewareTCPAssertion) {
	t.Helper()
	assert.Partial(t, GetMiddlewareTCP(env, t, name), asn, name)
}

// GetServersTransport fetches a ServersTransport by name via the dynamic client, failing the test on error.
func GetServersTransport(env *env.Env, t *testing.T, name string) *v1alpha1.ServersTransport {
	t.Helper()
	obj, err := GetServersTransportE(env, t, name)
	require.NoError(t, err, "failed to get ServersTransport %s", name)
	return obj
}

// GetServersTransportE fetches a ServersTransport by name via the dynamic client, returning the error for non-existence checks.
func GetServersTransportE(env *env.Env, t *testing.T, name string) (*v1alpha1.ServersTransport, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "traefik.io",
		Resource: "serverstransports",
		Version:  "v1alpha1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1alpha1.ServersTransport
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert ServersTransport from unstructured: %w", err)
	}
	return &out, nil
}

// AssertServersTransport fetches a ServersTransport and runs a partial assertion against it.
func AssertServersTransport(env *env.Env, t *testing.T, name string, asn v1alpha11.ServersTransportAssertion) {
	t.Helper()
	assert.Partial(t, GetServersTransport(env, t, name), asn, name)
}

// GetServersTransportTCP fetches a ServersTransportTCP by name via the dynamic client, failing the test on error.
func GetServersTransportTCP(env *env.Env, t *testing.T, name string) *v1alpha1.ServersTransportTCP {
	t.Helper()
	obj, err := GetServersTransportTCPE(env, t, name)
	require.NoError(t, err, "failed to get ServersTransportTCP %s", name)
	return obj
}

// GetServersTransportTCPE fetches a ServersTransportTCP by name via the dynamic client, returning the error for non-existence checks.
func GetServersTransportTCPE(env *env.Env, t *testing.T, name string) (*v1alpha1.ServersTransportTCP, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "traefik.io",
		Resource: "serverstransporttcps",
		Version:  "v1alpha1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1alpha1.ServersTransportTCP
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert ServersTransportTCP from unstructured: %w", err)
	}
	return &out, nil
}

// AssertServersTransportTCP fetches a ServersTransportTCP and runs a partial assertion against it.
func AssertServersTransportTCP(env *env.Env, t *testing.T, name string, asn v1alpha11.ServersTransportTCPAssertion) {
	t.Helper()
	assert.Partial(t, GetServersTransportTCP(env, t, name), asn, name)
}

// GetTLSOption fetches a TLSOption by name via the dynamic client, failing the test on error.
func GetTLSOption(env *env.Env, t *testing.T, name string) *v1alpha1.TLSOption {
	t.Helper()
	obj, err := GetTLSOptionE(env, t, name)
	require.NoError(t, err, "failed to get TLSOption %s", name)
	return obj
}

// GetTLSOptionE fetches a TLSOption by name via the dynamic client, returning the error for non-existence checks.
func GetTLSOptionE(env *env.Env, t *testing.T, name string) (*v1alpha1.TLSOption, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "traefik.io",
		Resource: "tlsoptions",
		Version:  "v1alpha1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1alpha1.TLSOption
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert TLSOption from unstructured: %w", err)
	}
	return &out, nil
}

// AssertTLSOption fetches a TLSOption and runs a partial assertion against it.
func AssertTLSOption(env *env.Env, t *testing.T, name string, asn v1alpha11.TLSOptionAssertion) {
	t.Helper()
	assert.Partial(t, GetTLSOption(env, t, name), asn, name)
}

// GetTLSStore fetches a TLSStore by name via the dynamic client, failing the test on error.
func GetTLSStore(env *env.Env, t *testing.T, name string) *v1alpha1.TLSStore {
	t.Helper()
	obj, err := GetTLSStoreE(env, t, name)
	require.NoError(t, err, "failed to get TLSStore %s", name)
	return obj
}

// GetTLSStoreE fetches a TLSStore by name via the dynamic client, returning the error for non-existence checks.
func GetTLSStoreE(env *env.Env, t *testing.T, name string) (*v1alpha1.TLSStore, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "traefik.io",
		Resource: "tlsstores",
		Version:  "v1alpha1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1alpha1.TLSStore
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert TLSStore from unstructured: %w", err)
	}
	return &out, nil
}

// AssertTLSStore fetches a TLSStore and runs a partial assertion against it.
func AssertTLSStore(env *env.Env, t *testing.T, name string, asn v1alpha11.TLSStoreAssertion) {
	t.Helper()
	assert.Partial(t, GetTLSStore(env, t, name), asn, name)
}

// GetTraefikService fetches a TraefikService by name via the dynamic client, failing the test on error.
func GetTraefikService(env *env.Env, t *testing.T, name string) *v1alpha1.TraefikService {
	t.Helper()
	obj, err := GetTraefikServiceE(env, t, name)
	require.NoError(t, err, "failed to get TraefikService %s", name)
	return obj
}

// GetTraefikServiceE fetches a TraefikService by name via the dynamic client, returning the error for non-existence checks.
func GetTraefikServiceE(env *env.Env, t *testing.T, name string) (*v1alpha1.TraefikService, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "traefik.io",
		Resource: "traefikservices",
		Version:  "v1alpha1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1alpha1.TraefikService
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert TraefikService from unstructured: %w", err)
	}
	return &out, nil
}

// AssertTraefikService fetches a TraefikService and runs a partial assertion against it.
func AssertTraefikService(env *env.Env, t *testing.T, name string, asn v1alpha11.TraefikServiceAssertion) {
	t.Helper()
	assert.Partial(t, GetTraefikService(env, t, name), asn, name)
}

// AssertPartial dispatches assertion to the matching Assert<Kind> based on
// the concrete type of assertion.
func AssertPartial(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch a := assertion.(type) {
	case v1alpha11.IngressRouteAssertion:
		AssertIngressRoute(env, t, name, a)
	case *v1alpha11.IngressRouteAssertion:
		AssertIngressRoute(env, t, name, *a)
	case v1alpha11.IngressRouteTCPAssertion:
		AssertIngressRouteTCP(env, t, name, a)
	case *v1alpha11.IngressRouteTCPAssertion:
		AssertIngressRouteTCP(env, t, name, *a)
	case v1alpha11.IngressRouteUDPAssertion:
		AssertIngressRouteUDP(env, t, name, a)
	case *v1alpha11.IngressRouteUDPAssertion:
		AssertIngressRouteUDP(env, t, name, *a)
	case v1alpha11.MiddlewareAssertion:
		AssertMiddleware(env, t, name, a)
	case *v1alpha11.MiddlewareAssertion:
		AssertMiddleware(env, t, name, *a)
	case v1alpha11.MiddlewareTCPAssertion:
		AssertMiddlewareTCP(env, t, name, a)
	case *v1alpha11.MiddlewareTCPAssertion:
		AssertMiddlewareTCP(env, t, name, *a)
	case v1alpha11.ServersTransportAssertion:
		AssertServersTransport(env, t, name, a)
	case *v1alpha11.ServersTransportAssertion:
		AssertServersTransport(env, t, name, *a)
	case v1alpha11.ServersTransportTCPAssertion:
		AssertServersTransportTCP(env, t, name, a)
	case *v1alpha11.ServersTransportTCPAssertion:
		AssertServersTransportTCP(env, t, name, *a)
	case v1alpha11.TLSOptionAssertion:
		AssertTLSOption(env, t, name, a)
	case *v1alpha11.TLSOptionAssertion:
		AssertTLSOption(env, t, name, *a)
	case v1alpha11.TLSStoreAssertion:
		AssertTLSStore(env, t, name, a)
	case *v1alpha11.TLSStoreAssertion:
		AssertTLSStore(env, t, name, *a)
	case v1alpha11.TraefikServiceAssertion:
		AssertTraefikService(env, t, name, a)
	case *v1alpha11.TraefikServiceAssertion:
		AssertTraefikService(env, t, name, *a)
	default:
		t.Fatalf("AssertPartial: no Kind registered for assertion type %T", assertion)
	}
}

// AssertNone asserts that the Kind implied by assertion does not exist
// (the dynamic-client GET returns NotFound).
func AssertNone(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch assertion.(type) {
	case v1alpha11.IngressRouteAssertion, *v1alpha11.IngressRouteAssertion:
		_, err := GetIngressRouteE(env, t, name)
		require.True(t, errors.IsNotFound(err), "IngressRoute %q should not exist (err: %v)", name, err)
	case v1alpha11.IngressRouteTCPAssertion, *v1alpha11.IngressRouteTCPAssertion:
		_, err := GetIngressRouteTCPE(env, t, name)
		require.True(t, errors.IsNotFound(err), "IngressRouteTCP %q should not exist (err: %v)", name, err)
	case v1alpha11.IngressRouteUDPAssertion, *v1alpha11.IngressRouteUDPAssertion:
		_, err := GetIngressRouteUDPE(env, t, name)
		require.True(t, errors.IsNotFound(err), "IngressRouteUDP %q should not exist (err: %v)", name, err)
	case v1alpha11.MiddlewareAssertion, *v1alpha11.MiddlewareAssertion:
		_, err := GetMiddlewareE(env, t, name)
		require.True(t, errors.IsNotFound(err), "Middleware %q should not exist (err: %v)", name, err)
	case v1alpha11.MiddlewareTCPAssertion, *v1alpha11.MiddlewareTCPAssertion:
		_, err := GetMiddlewareTCPE(env, t, name)
		require.True(t, errors.IsNotFound(err), "MiddlewareTCP %q should not exist (err: %v)", name, err)
	case v1alpha11.ServersTransportAssertion, *v1alpha11.ServersTransportAssertion:
		_, err := GetServersTransportE(env, t, name)
		require.True(t, errors.IsNotFound(err), "ServersTransport %q should not exist (err: %v)", name, err)
	case v1alpha11.ServersTransportTCPAssertion, *v1alpha11.ServersTransportTCPAssertion:
		_, err := GetServersTransportTCPE(env, t, name)
		require.True(t, errors.IsNotFound(err), "ServersTransportTCP %q should not exist (err: %v)", name, err)
	case v1alpha11.TLSOptionAssertion, *v1alpha11.TLSOptionAssertion:
		_, err := GetTLSOptionE(env, t, name)
		require.True(t, errors.IsNotFound(err), "TLSOption %q should not exist (err: %v)", name, err)
	case v1alpha11.TLSStoreAssertion, *v1alpha11.TLSStoreAssertion:
		_, err := GetTLSStoreE(env, t, name)
		require.True(t, errors.IsNotFound(err), "TLSStore %q should not exist (err: %v)", name, err)
	case v1alpha11.TraefikServiceAssertion, *v1alpha11.TraefikServiceAssertion:
		_, err := GetTraefikServiceE(env, t, name)
		require.True(t, errors.IsNotFound(err), "TraefikService %q should not exist (err: %v)", name, err)
	default:
		t.Fatalf("AssertNone: no Kind registered for assertion type %T", assertion)
	}
}
