// Code generated by assertgen. DO NOT EDIT.

package v1

import (
	v13 "github.com/cert-manager/cert-manager/pkg/apis/acme/v1"
	v11 "github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1"
	v12 "github.com/cert-manager/cert-manager/pkg/apis/meta/v1"
	assert "github.com/mridang/wilhelm/assert"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CAIssuerAssertion is the assertion struct for CAIssuer.
type CAIssuerAssertion struct {
	SecretName             assert.Opt[string]
	CRLDistributionPoints  assert.Opt[[]string]
	OCSPServers            assert.Opt[[]string]
	IssuingCertificateURLs assert.Opt[[]string]
}

// IsAssertable marks CAIssuerAssertion as an Assertable.
func (_ CAIssuerAssertion) IsAssertable() {}

// CertificateAssertion is the assertion struct for Certificate.
type CertificateAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       CertificateSpecAssertion
	Status     assert.Opt[v11.CertificateStatus]
}

// IsAssertable marks CertificateAssertion as an Assertable.
func (_ CertificateAssertion) IsAssertable() {}

// CertificateAdditionalOutputFormatAssertion is the assertion struct for CertificateAdditionalOutputFormat.
type CertificateAdditionalOutputFormatAssertion struct {
	Type assert.Opt[v11.CertificateOutputFormatType]
}

// IsAssertable marks CertificateAdditionalOutputFormatAssertion as an Assertable.
func (_ CertificateAdditionalOutputFormatAssertion) IsAssertable() {}

// CertificateConditionAssertion is the assertion struct for CertificateCondition.
type CertificateConditionAssertion struct {
	Type               assert.Opt[v11.CertificateConditionType]
	Status             assert.Opt[v12.ConditionStatus]
	LastTransitionTime assert.Opt[*v1.Time]
	Reason             assert.Opt[string]
	Message            assert.Opt[string]
	ObservedGeneration assert.Opt[int64]
}

// IsAssertable marks CertificateConditionAssertion as an Assertable.
func (_ CertificateConditionAssertion) IsAssertable() {}

// CertificateKeystoresAssertion is the assertion struct for CertificateKeystores.
type CertificateKeystoresAssertion struct {
	JKS    JKSKeystoreAssertion
	PKCS12 PKCS12KeystoreAssertion
}

// IsAssertable marks CertificateKeystoresAssertion as an Assertable.
func (_ CertificateKeystoresAssertion) IsAssertable() {}

// CertificatePrivateKeyAssertion is the assertion struct for CertificatePrivateKey.
type CertificatePrivateKeyAssertion struct {
	RotationPolicy assert.Opt[v11.PrivateKeyRotationPolicy]
	Encoding       assert.Opt[v11.PrivateKeyEncoding]
	Algorithm      assert.Opt[v11.PrivateKeyAlgorithm]
	Size           assert.Opt[int]
}

// IsAssertable marks CertificatePrivateKeyAssertion as an Assertable.
func (_ CertificatePrivateKeyAssertion) IsAssertable() {}

// CertificateRequestAssertion is the assertion struct for CertificateRequest.
type CertificateRequestAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       CertificateRequestSpecAssertion
	Status     assert.Opt[v11.CertificateRequestStatus]
}

// IsAssertable marks CertificateRequestAssertion as an Assertable.
func (_ CertificateRequestAssertion) IsAssertable() {}

// CertificateRequestConditionAssertion is the assertion struct for CertificateRequestCondition.
type CertificateRequestConditionAssertion struct {
	Type               assert.Opt[v11.CertificateRequestConditionType]
	Status             assert.Opt[v12.ConditionStatus]
	LastTransitionTime assert.Opt[*v1.Time]
	Reason             assert.Opt[string]
	Message            assert.Opt[string]
}

// IsAssertable marks CertificateRequestConditionAssertion as an Assertable.
func (_ CertificateRequestConditionAssertion) IsAssertable() {}

// CertificateRequestSpecAssertion is the assertion struct for CertificateRequestSpec.
type CertificateRequestSpecAssertion struct {
	Duration  assert.Opt[*v1.Duration]
	IssuerRef assert.Opt[v12.IssuerReference]
	Request   assert.Opt[[]byte]
	IsCA      assert.Opt[bool]
	Usages    assert.Opt[[]v11.KeyUsage]
	Username  assert.Opt[string]
	UID       assert.Opt[string]
	Groups    assert.Opt[[]string]
	Extra     assert.Opt[map[string][]string]
}

// IsAssertable marks CertificateRequestSpecAssertion as an Assertable.
func (_ CertificateRequestSpecAssertion) IsAssertable() {}

// CertificateSecretTemplateAssertion is the assertion struct for CertificateSecretTemplate.
type CertificateSecretTemplateAssertion struct {
	Annotations assert.Opt[map[string]string]
	Labels      assert.Opt[map[string]string]
}

// IsAssertable marks CertificateSecretTemplateAssertion as an Assertable.
func (_ CertificateSecretTemplateAssertion) IsAssertable() {}

// CertificateSpecAssertion is the assertion struct for CertificateSpec.
type CertificateSpecAssertion struct {
	Subject                 X509SubjectAssertion
	LiteralSubject          assert.Opt[string]
	CommonName              assert.Opt[string]
	Duration                assert.Opt[*v1.Duration]
	RenewBefore             assert.Opt[*v1.Duration]
	RenewBeforePercentage   assert.Opt[*int32]
	DNSNames                assert.Opt[[]string]
	IPAddresses             assert.Opt[[]string]
	URIs                    assert.Opt[[]string]
	OtherNames              assert.Opt[[]OtherNameAssertion]
	EmailAddresses          assert.Opt[[]string]
	SecretName              assert.Opt[string]
	SecretTemplate          CertificateSecretTemplateAssertion
	Keystores               CertificateKeystoresAssertion
	IssuerRef               assert.Opt[v12.IssuerReference]
	IsCA                    assert.Opt[bool]
	Usages                  assert.Opt[[]v11.KeyUsage]
	PrivateKey              CertificatePrivateKeyAssertion
	SignatureAlgorithm      assert.Opt[v11.SignatureAlgorithm]
	EncodeUsagesInRequest   assert.Opt[*bool]
	RevisionHistoryLimit    assert.Opt[*int32]
	AdditionalOutputFormats assert.Opt[[]CertificateAdditionalOutputFormatAssertion]
	NameConstraints         NameConstraintsAssertion
}

// IsAssertable marks CertificateSpecAssertion as an Assertable.
func (_ CertificateSpecAssertion) IsAssertable() {}

// ClusterIssuerAssertion is the assertion struct for ClusterIssuer.
type ClusterIssuerAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       IssuerSpecAssertion
	Status     assert.Opt[v11.IssuerStatus]
}

// IsAssertable marks ClusterIssuerAssertion as an Assertable.
func (_ ClusterIssuerAssertion) IsAssertable() {}

// IssuerAssertion is the assertion struct for Issuer.
type IssuerAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       IssuerSpecAssertion
	Status     assert.Opt[v11.IssuerStatus]
}

// IsAssertable marks IssuerAssertion as an Assertable.
func (_ IssuerAssertion) IsAssertable() {}

// IssuerConditionAssertion is the assertion struct for IssuerCondition.
type IssuerConditionAssertion struct {
	Type               assert.Opt[v11.IssuerConditionType]
	Status             assert.Opt[v12.ConditionStatus]
	LastTransitionTime assert.Opt[*v1.Time]
	Reason             assert.Opt[string]
	Message            assert.Opt[string]
	ObservedGeneration assert.Opt[int64]
}

// IsAssertable marks IssuerConditionAssertion as an Assertable.
func (_ IssuerConditionAssertion) IsAssertable() {}

// IssuerConfigAssertion is the assertion struct for IssuerConfig.
type IssuerConfigAssertion struct {
	ACME       assert.Opt[*v13.ACMEIssuer]
	CA         CAIssuerAssertion
	Vault      VaultIssuerAssertion
	SelfSigned SelfSignedIssuerAssertion
	Venafi     VenafiIssuerAssertion
}

// IsAssertable marks IssuerConfigAssertion as an Assertable.
func (_ IssuerConfigAssertion) IsAssertable() {}

// IssuerSpecAssertion is the assertion struct for IssuerSpec.
type IssuerSpecAssertion struct {
	IssuerConfig IssuerConfigAssertion
}

// IsAssertable marks IssuerSpecAssertion as an Assertable.
func (_ IssuerSpecAssertion) IsAssertable() {}

// JKSKeystoreAssertion is the assertion struct for JKSKeystore.
type JKSKeystoreAssertion struct {
	Create            assert.Opt[bool]
	Alias             assert.Opt[*string]
	PasswordSecretRef assert.Opt[v12.SecretKeySelector]
	Password          assert.Opt[*string]
}

// IsAssertable marks JKSKeystoreAssertion as an Assertable.
func (_ JKSKeystoreAssertion) IsAssertable() {}

// NameConstraintItemAssertion is the assertion struct for NameConstraintItem.
type NameConstraintItemAssertion struct {
	DNSDomains     assert.Opt[[]string]
	IPRanges       assert.Opt[[]string]
	EmailAddresses assert.Opt[[]string]
	URIDomains     assert.Opt[[]string]
}

// IsAssertable marks NameConstraintItemAssertion as an Assertable.
func (_ NameConstraintItemAssertion) IsAssertable() {}

// NameConstraintsAssertion is the assertion struct for NameConstraints.
type NameConstraintsAssertion struct {
	Critical  assert.Opt[bool]
	Permitted NameConstraintItemAssertion
	Excluded  NameConstraintItemAssertion
}

// IsAssertable marks NameConstraintsAssertion as an Assertable.
func (_ NameConstraintsAssertion) IsAssertable() {}

// OtherNameAssertion is the assertion struct for OtherName.
type OtherNameAssertion struct {
	OID       assert.Opt[string]
	UTF8Value assert.Opt[string]
}

// IsAssertable marks OtherNameAssertion as an Assertable.
func (_ OtherNameAssertion) IsAssertable() {}

// PKCS12KeystoreAssertion is the assertion struct for PKCS12Keystore.
type PKCS12KeystoreAssertion struct {
	Create            assert.Opt[bool]
	Profile           assert.Opt[v11.PKCS12Profile]
	PasswordSecretRef assert.Opt[v12.SecretKeySelector]
	Password          assert.Opt[*string]
}

// IsAssertable marks PKCS12KeystoreAssertion as an Assertable.
func (_ PKCS12KeystoreAssertion) IsAssertable() {}

// SchemeGroupVersionAssertion is the assertion struct for GroupVersion.
type SchemeGroupVersionAssertion struct {
	Group   assert.Opt[string]
	Version assert.Opt[string]
}

// IsAssertable marks SchemeGroupVersionAssertion as an Assertable.
func (_ SchemeGroupVersionAssertion) IsAssertable() {}

// SelfSignedIssuerAssertion is the assertion struct for SelfSignedIssuer.
type SelfSignedIssuerAssertion struct {
	CRLDistributionPoints assert.Opt[[]string]
}

// IsAssertable marks SelfSignedIssuerAssertion as an Assertable.
func (_ SelfSignedIssuerAssertion) IsAssertable() {}

// ServiceAccountRefAssertion is the assertion struct for ServiceAccountRef.
type ServiceAccountRefAssertion struct {
	Name           assert.Opt[string]
	TokenAudiences assert.Opt[[]string]
}

// IsAssertable marks ServiceAccountRefAssertion as an Assertable.
func (_ ServiceAccountRefAssertion) IsAssertable() {}

// VaultAppRoleAssertion is the assertion struct for VaultAppRole.
type VaultAppRoleAssertion struct {
	Path      assert.Opt[string]
	RoleId    assert.Opt[string]
	SecretRef assert.Opt[v12.SecretKeySelector]
}

// IsAssertable marks VaultAppRoleAssertion as an Assertable.
func (_ VaultAppRoleAssertion) IsAssertable() {}

// VaultAuthAssertion is the assertion struct for VaultAuth.
type VaultAuthAssertion struct {
	TokenSecretRef    assert.Opt[*v12.SecretKeySelector]
	AppRole           VaultAppRoleAssertion
	ClientCertificate VaultClientCertificateAuthAssertion
	Kubernetes        VaultKubernetesAuthAssertion
}

// IsAssertable marks VaultAuthAssertion as an Assertable.
func (_ VaultAuthAssertion) IsAssertable() {}

// VaultClientCertificateAuthAssertion is the assertion struct for VaultClientCertificateAuth.
type VaultClientCertificateAuthAssertion struct {
	Path       assert.Opt[string]
	SecretName assert.Opt[string]
	Name       assert.Opt[string]
}

// IsAssertable marks VaultClientCertificateAuthAssertion as an Assertable.
func (_ VaultClientCertificateAuthAssertion) IsAssertable() {}

// VaultIssuerAssertion is the assertion struct for VaultIssuer.
type VaultIssuerAssertion struct {
	Auth                VaultAuthAssertion
	Server              assert.Opt[string]
	ServerName          assert.Opt[string]
	Path                assert.Opt[string]
	Namespace           assert.Opt[string]
	CABundle            assert.Opt[[]byte]
	CABundleSecretRef   assert.Opt[*v12.SecretKeySelector]
	ClientCertSecretRef assert.Opt[*v12.SecretKeySelector]
	ClientKeySecretRef  assert.Opt[*v12.SecretKeySelector]
}

// IsAssertable marks VaultIssuerAssertion as an Assertable.
func (_ VaultIssuerAssertion) IsAssertable() {}

// VaultKubernetesAuthAssertion is the assertion struct for VaultKubernetesAuth.
type VaultKubernetesAuthAssertion struct {
	Path              assert.Opt[string]
	SecretRef         assert.Opt[v12.SecretKeySelector]
	ServiceAccountRef ServiceAccountRefAssertion
	Role              assert.Opt[string]
}

// IsAssertable marks VaultKubernetesAuthAssertion as an Assertable.
func (_ VaultKubernetesAuthAssertion) IsAssertable() {}

// VenafiCloudAssertion is the assertion struct for VenafiCloud.
type VenafiCloudAssertion struct {
	URL               assert.Opt[string]
	APITokenSecretRef assert.Opt[v12.SecretKeySelector]
}

// IsAssertable marks VenafiCloudAssertion as an Assertable.
func (_ VenafiCloudAssertion) IsAssertable() {}

// VenafiIssuerAssertion is the assertion struct for VenafiIssuer.
type VenafiIssuerAssertion struct {
	Zone  assert.Opt[string]
	TPP   VenafiTPPAssertion
	Cloud VenafiCloudAssertion
}

// IsAssertable marks VenafiIssuerAssertion as an Assertable.
func (_ VenafiIssuerAssertion) IsAssertable() {}

// VenafiTPPAssertion is the assertion struct for VenafiTPP.
type VenafiTPPAssertion struct {
	URL               assert.Opt[string]
	CredentialsRef    assert.Opt[v12.LocalObjectReference]
	CABundle          assert.Opt[[]byte]
	CABundleSecretRef assert.Opt[*v12.SecretKeySelector]
}

// IsAssertable marks VenafiTPPAssertion as an Assertable.
func (_ VenafiTPPAssertion) IsAssertable() {}

// X509SubjectAssertion is the assertion struct for X509Subject.
type X509SubjectAssertion struct {
	Organizations       assert.Opt[[]string]
	Countries           assert.Opt[[]string]
	OrganizationalUnits assert.Opt[[]string]
	Localities          assert.Opt[[]string]
	Provinces           assert.Opt[[]string]
	StreetAddresses     assert.Opt[[]string]
	PostalCodes         assert.Opt[[]string]
	SerialNumber        assert.Opt[string]
}

// IsAssertable marks X509SubjectAssertion as an Assertable.
func (_ X509SubjectAssertion) IsAssertable() {}
