// Code generated by assertgen. DO NOT EDIT.

package v1

import (
	assert "github.com/mridang/wilhelm/assert"
	config "github.com/tektoncd/pipeline/pkg/apis/config"
	pod "github.com/tektoncd/pipeline/pkg/apis/pipeline/pod"
	v1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	v12 "k8s.io/api/core/v1"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	selection "k8s.io/apimachinery/pkg/selection"
)

// ArtifactAssertion is the assertion struct for Artifact.
type ArtifactAssertion struct {
	Name        assert.Opt[string]
	Values      assert.Opt[[]ArtifactValueAssertion]
	BuildOutput assert.Opt[bool]
}

// IsAssertable marks ArtifactAssertion as an Assertable.
func (_ ArtifactAssertion) IsAssertable() {}

// ArtifactValueAssertion is the assertion struct for ArtifactValue.
type ArtifactValueAssertion struct {
	Digest assert.Opt[map[v1.Algorithm]string]
	Uri    assert.Opt[string]
}

// IsAssertable marks ArtifactValueAssertion as an Assertable.
func (_ ArtifactValueAssertion) IsAssertable() {}

// ArtifactsAssertion is the assertion struct for Artifacts.
type ArtifactsAssertion struct {
	Inputs  assert.Opt[[]ArtifactAssertion]
	Outputs assert.Opt[[]ArtifactAssertion]
}

// IsAssertable marks ArtifactsAssertion as an Assertable.
func (_ ArtifactsAssertion) IsAssertable() {}

// ChildStatusReferenceAssertion is the assertion struct for ChildStatusReference.
type ChildStatusReferenceAssertion struct {
	TypeMeta         assert.Opt[runtime.TypeMeta]
	Name             assert.Opt[string]
	DisplayName      assert.Opt[string]
	PipelineTaskName assert.Opt[string]
	WhenExpressions  assert.Opt[[]WhenExpressionAssertion]
}

// IsAssertable marks ChildStatusReferenceAssertion as an Assertable.
func (_ ChildStatusReferenceAssertion) IsAssertable() {}

// EmbeddedTaskAssertion is the assertion struct for EmbeddedTask.
type EmbeddedTaskAssertion struct {
	TypeMeta assert.Opt[runtime.TypeMeta]
	Spec     assert.Opt[runtime.RawExtension]
	Metadata PipelineTaskMetadataAssertion
	TaskSpec TaskSpecAssertion
}

// IsAssertable marks EmbeddedTaskAssertion as an Assertable.
func (_ EmbeddedTaskAssertion) IsAssertable() {}

// IncludeParamsAssertion is the assertion struct for IncludeParams.
type IncludeParamsAssertion struct {
	Name   assert.Opt[string]
	Params assert.Opt[v1.Params]
}

// IsAssertable marks IncludeParamsAssertion as an Assertable.
func (_ IncludeParamsAssertion) IsAssertable() {}

// MatrixAssertion is the assertion struct for Matrix.
type MatrixAssertion struct {
	Params  assert.Opt[v1.Params]
	Include assert.Opt[v1.IncludeParamsList]
}

// IsAssertable marks MatrixAssertion as an Assertable.
func (_ MatrixAssertion) IsAssertable() {}

// ParamAssertion is the assertion struct for Param.
type ParamAssertion struct {
	Name  assert.Opt[string]
	Value ParamValueAssertion
}

// IsAssertable marks ParamAssertion as an Assertable.
func (_ ParamAssertion) IsAssertable() {}

// ParamSpecAssertion is the assertion struct for ParamSpec.
type ParamSpecAssertion struct {
	Name        assert.Opt[string]
	Type        assert.Opt[v1.ParamType]
	Description assert.Opt[string]
	Properties  assert.Opt[map[string]v1.PropertySpec]
	Default     ParamValueAssertion
	Enum        assert.Opt[[]string]
}

// IsAssertable marks ParamSpecAssertion as an Assertable.
func (_ ParamSpecAssertion) IsAssertable() {}

// ParamValueAssertion is the assertion struct for ParamValue.
type ParamValueAssertion struct {
	Type      assert.Opt[v1.ParamType]
	StringVal assert.Opt[string]
	ArrayVal  assert.Opt[[]string]
	ObjectVal assert.Opt[map[string]string]
}

// IsAssertable marks ParamValueAssertion as an Assertable.
func (_ ParamValueAssertion) IsAssertable() {}

// PipelineAssertion is the assertion struct for Pipeline.
type PipelineAssertion struct {
	TypeMeta   assert.Opt[v11.TypeMeta]
	ObjectMeta assert.Opt[v11.ObjectMeta]
	Spec       PipelineSpecAssertion
}

// IsAssertable marks PipelineAssertion as an Assertable.
func (_ PipelineAssertion) IsAssertable() {}

// PipelineRefAssertion is the assertion struct for PipelineRef.
type PipelineRefAssertion struct {
	Name        assert.Opt[string]
	APIVersion  assert.Opt[string]
	ResolverRef ResolverRefAssertion
}

// IsAssertable marks PipelineRefAssertion as an Assertable.
func (_ PipelineRefAssertion) IsAssertable() {}

// PipelineResultAssertion is the assertion struct for PipelineResult.
type PipelineResultAssertion struct {
	Name        assert.Opt[string]
	Type        assert.Opt[v1.ResultsType]
	Description assert.Opt[string]
	Value       assert.Opt[v1.ResultValue]
}

// IsAssertable marks PipelineResultAssertion as an Assertable.
func (_ PipelineResultAssertion) IsAssertable() {}

// PipelineRunAssertion is the assertion struct for PipelineRun.
type PipelineRunAssertion struct {
	TypeMeta   assert.Opt[v11.TypeMeta]
	ObjectMeta assert.Opt[v11.ObjectMeta]
	Spec       PipelineRunSpecAssertion
	Status     assert.Opt[v1.PipelineRunStatus]
}

// IsAssertable marks PipelineRunAssertion as an Assertable.
func (_ PipelineRunAssertion) IsAssertable() {}

// PipelineRunResultAssertion is the assertion struct for PipelineRunResult.
type PipelineRunResultAssertion struct {
	Name  assert.Opt[string]
	Value assert.Opt[v1.ResultValue]
}

// IsAssertable marks PipelineRunResultAssertion as an Assertable.
func (_ PipelineRunResultAssertion) IsAssertable() {}

// PipelineRunSpecAssertion is the assertion struct for PipelineRunSpec.
type PipelineRunSpecAssertion struct {
	PipelineRef     PipelineRefAssertion
	PipelineSpec    PipelineSpecAssertion
	Params          assert.Opt[v1.Params]
	Status          assert.Opt[v1.PipelineRunSpecStatus]
	Timeouts        TimeoutFieldsAssertion
	TaskRunTemplate PipelineTaskRunTemplateAssertion
	Workspaces      assert.Opt[[]WorkspaceBindingAssertion]
	TaskRunSpecs    assert.Opt[[]PipelineTaskRunSpecAssertion]
	ManagedBy       assert.Opt[*string]
}

// IsAssertable marks PipelineRunSpecAssertion as an Assertable.
func (_ PipelineRunSpecAssertion) IsAssertable() {}

// PipelineRunStatusFieldsAssertion is the assertion struct for PipelineRunStatusFields.
type PipelineRunStatusFieldsAssertion struct {
	StartTime        assert.Opt[*v11.Time]
	CompletionTime   assert.Opt[*v11.Time]
	Results          assert.Opt[[]PipelineRunResultAssertion]
	PipelineSpec     PipelineSpecAssertion
	SkippedTasks     assert.Opt[[]SkippedTaskAssertion]
	ChildReferences  assert.Opt[[]ChildStatusReferenceAssertion]
	FinallyStartTime assert.Opt[*v11.Time]
	Provenance       ProvenanceAssertion
	SpanContext      assert.Opt[map[string]string]
}

// IsAssertable marks PipelineRunStatusFieldsAssertion as an Assertable.
func (_ PipelineRunStatusFieldsAssertion) IsAssertable() {}

// PipelineSpecAssertion is the assertion struct for PipelineSpec.
type PipelineSpecAssertion struct {
	DisplayName assert.Opt[string]
	Description assert.Opt[string]
	Tasks       assert.Opt[[]PipelineTaskAssertion]
	Params      assert.Opt[v1.ParamSpecs]
	Workspaces  assert.Opt[[]PipelineWorkspaceDeclarationAssertion]
	Results     assert.Opt[[]PipelineResultAssertion]
	Finally     assert.Opt[[]PipelineTaskAssertion]
}

// IsAssertable marks PipelineSpecAssertion as an Assertable.
func (_ PipelineSpecAssertion) IsAssertable() {}

// PipelineTaskAssertion is the assertion struct for PipelineTask.
type PipelineTaskAssertion struct {
	Name         assert.Opt[string]
	DisplayName  assert.Opt[string]
	Description  assert.Opt[string]
	TaskRef      TaskRefAssertion
	TaskSpec     EmbeddedTaskAssertion
	When         assert.Opt[v1.WhenExpressions]
	Retries      assert.Opt[int]
	RunAfter     assert.Opt[[]string]
	Params       assert.Opt[v1.Params]
	Matrix       MatrixAssertion
	Workspaces   assert.Opt[[]WorkspacePipelineTaskBindingAssertion]
	Timeout      assert.Opt[*v11.Duration]
	PipelineRef  PipelineRefAssertion
	PipelineSpec PipelineSpecAssertion
	OnError      assert.Opt[v1.PipelineTaskOnErrorType]
}

// IsAssertable marks PipelineTaskAssertion as an Assertable.
func (_ PipelineTaskAssertion) IsAssertable() {}

// PipelineTaskMetadataAssertion is the assertion struct for PipelineTaskMetadata.
type PipelineTaskMetadataAssertion struct {
	Labels      assert.Opt[map[string]string]
	Annotations assert.Opt[map[string]string]
}

// IsAssertable marks PipelineTaskMetadataAssertion as an Assertable.
func (_ PipelineTaskMetadataAssertion) IsAssertable() {}

// PipelineTaskParamAssertion is the assertion struct for PipelineTaskParam.
type PipelineTaskParamAssertion struct {
	Name  assert.Opt[string]
	Value assert.Opt[string]
}

// IsAssertable marks PipelineTaskParamAssertion as an Assertable.
func (_ PipelineTaskParamAssertion) IsAssertable() {}

// PipelineTaskRunAssertion is the assertion struct for PipelineTaskRun.
type PipelineTaskRunAssertion struct {
	Name assert.Opt[string]
}

// IsAssertable marks PipelineTaskRunAssertion as an Assertable.
func (_ PipelineTaskRunAssertion) IsAssertable() {}

// PipelineTaskRunSpecAssertion is the assertion struct for PipelineTaskRunSpec.
type PipelineTaskRunSpecAssertion struct {
	PipelineTaskName   assert.Opt[string]
	ServiceAccountName assert.Opt[string]
	PodTemplate        assert.Opt[*pod.PodTemplate]
	StepSpecs          assert.Opt[[]TaskRunStepSpecAssertion]
	SidecarSpecs       assert.Opt[[]TaskRunSidecarSpecAssertion]
	Metadata           PipelineTaskMetadataAssertion
	ComputeResources   assert.Opt[*v12.ResourceRequirements]
	Timeout            assert.Opt[*v11.Duration]
}

// IsAssertable marks PipelineTaskRunSpecAssertion as an Assertable.
func (_ PipelineTaskRunSpecAssertion) IsAssertable() {}

// PipelineTaskRunTemplateAssertion is the assertion struct for PipelineTaskRunTemplate.
type PipelineTaskRunTemplateAssertion struct {
	PodTemplate        assert.Opt[*pod.PodTemplate]
	ServiceAccountName assert.Opt[string]
}

// IsAssertable marks PipelineTaskRunTemplateAssertion as an Assertable.
func (_ PipelineTaskRunTemplateAssertion) IsAssertable() {}

// PipelineWorkspaceDeclarationAssertion is the assertion struct for PipelineWorkspaceDeclaration.
type PipelineWorkspaceDeclarationAssertion struct {
	Name        assert.Opt[string]
	Description assert.Opt[string]
	Optional    assert.Opt[bool]
}

// IsAssertable marks PipelineWorkspaceDeclarationAssertion as an Assertable.
func (_ PipelineWorkspaceDeclarationAssertion) IsAssertable() {}

// PropertySpecAssertion is the assertion struct for PropertySpec.
type PropertySpecAssertion struct {
	Type assert.Opt[v1.ParamType]
}

// IsAssertable marks PropertySpecAssertion as an Assertable.
func (_ PropertySpecAssertion) IsAssertable() {}

// ProvenanceAssertion is the assertion struct for Provenance.
type ProvenanceAssertion struct {
	RefSource    RefSourceAssertion
	FeatureFlags assert.Opt[*config.FeatureFlags]
}

// IsAssertable marks ProvenanceAssertion as an Assertable.
func (_ ProvenanceAssertion) IsAssertable() {}

// RefAssertion is the assertion struct for Ref.
type RefAssertion struct {
	Name        assert.Opt[string]
	ResolverRef ResolverRefAssertion
}

// IsAssertable marks RefAssertion as an Assertable.
func (_ RefAssertion) IsAssertable() {}

// RefSourceAssertion is the assertion struct for RefSource.
type RefSourceAssertion struct {
	URI        assert.Opt[string]
	Digest     assert.Opt[map[string]string]
	EntryPoint assert.Opt[string]
}

// IsAssertable marks RefSourceAssertion as an Assertable.
func (_ RefSourceAssertion) IsAssertable() {}

// ResolverRefAssertion is the assertion struct for ResolverRef.
type ResolverRefAssertion struct {
	Resolver assert.Opt[v1.ResolverName]
	Params   assert.Opt[v1.Params]
}

// IsAssertable marks ResolverRefAssertion as an Assertable.
func (_ ResolverRefAssertion) IsAssertable() {}

// ResultRefAssertion is the assertion struct for ResultRef.
type ResultRefAssertion struct {
	PipelineTask assert.Opt[string]
	Result       assert.Opt[string]
	ResultsIndex assert.Opt[*int]
	Property     assert.Opt[string]
}

// IsAssertable marks ResultRefAssertion as an Assertable.
func (_ ResultRefAssertion) IsAssertable() {}

// SchemeGroupVersionAssertion is the assertion struct for GroupVersion.
type SchemeGroupVersionAssertion struct {
	Group   assert.Opt[string]
	Version assert.Opt[string]
}

// IsAssertable marks SchemeGroupVersionAssertion as an Assertable.
func (_ SchemeGroupVersionAssertion) IsAssertable() {}

// SidecarAssertion is the assertion struct for Sidecar.
type SidecarAssertion struct {
	Name                     assert.Opt[string]
	Image                    assert.Opt[string]
	Command                  assert.Opt[[]string]
	Args                     assert.Opt[[]string]
	WorkingDir               assert.Opt[string]
	Ports                    assert.Opt[[]v12.ContainerPort]
	EnvFrom                  assert.Opt[[]v12.EnvFromSource]
	Env                      assert.Opt[[]v12.EnvVar]
	ComputeResources         assert.Opt[v12.ResourceRequirements]
	VolumeMounts             assert.Opt[[]v12.VolumeMount]
	VolumeDevices            assert.Opt[[]v12.VolumeDevice]
	LivenessProbe            assert.Opt[*v12.Probe]
	ReadinessProbe           assert.Opt[*v12.Probe]
	StartupProbe             assert.Opt[*v12.Probe]
	Lifecycle                assert.Opt[*v12.Lifecycle]
	TerminationMessagePath   assert.Opt[string]
	TerminationMessagePolicy assert.Opt[v12.TerminationMessagePolicy]
	ImagePullPolicy          assert.Opt[v12.PullPolicy]
	SecurityContext          assert.Opt[*v12.SecurityContext]
	Stdin                    assert.Opt[bool]
	StdinOnce                assert.Opt[bool]
	TTY                      assert.Opt[bool]
	Script                   assert.Opt[string]
	Workspaces               assert.Opt[[]WorkspaceUsageAssertion]
	RestartPolicy            assert.Opt[*v12.ContainerRestartPolicy]
}

// IsAssertable marks SidecarAssertion as an Assertable.
func (_ SidecarAssertion) IsAssertable() {}

// SidecarStateAssertion is the assertion struct for SidecarState.
type SidecarStateAssertion struct {
	ContainerState assert.Opt[v12.ContainerState]
	Name           assert.Opt[string]
	Container      assert.Opt[string]
	ImageID        assert.Opt[string]
}

// IsAssertable marks SidecarStateAssertion as an Assertable.
func (_ SidecarStateAssertion) IsAssertable() {}

// SkippedTaskAssertion is the assertion struct for SkippedTask.
type SkippedTaskAssertion struct {
	Name            assert.Opt[string]
	Reason          assert.Opt[v1.SkippingReason]
	WhenExpressions assert.Opt[[]WhenExpressionAssertion]
}

// IsAssertable marks SkippedTaskAssertion as an Assertable.
func (_ SkippedTaskAssertion) IsAssertable() {}

// StepAssertion is the assertion struct for Step.
type StepAssertion struct {
	Name             assert.Opt[string]
	DisplayName      assert.Opt[string]
	Image            assert.Opt[string]
	Command          assert.Opt[[]string]
	Args             assert.Opt[[]string]
	WorkingDir       assert.Opt[string]
	EnvFrom          assert.Opt[[]v12.EnvFromSource]
	Env              assert.Opt[[]v12.EnvVar]
	ComputeResources assert.Opt[v12.ResourceRequirements]
	VolumeMounts     assert.Opt[[]v12.VolumeMount]
	VolumeDevices    assert.Opt[[]v12.VolumeDevice]
	ImagePullPolicy  assert.Opt[v12.PullPolicy]
	SecurityContext  assert.Opt[*v12.SecurityContext]
	Script           assert.Opt[string]
	Timeout          assert.Opt[*v11.Duration]
	Workspaces       assert.Opt[[]WorkspaceUsageAssertion]
	OnError          assert.Opt[v1.OnErrorType]
	StdoutConfig     StepOutputConfigAssertion
	StderrConfig     StepOutputConfigAssertion
	Ref              RefAssertion
	Params           assert.Opt[v1.Params]
	Results          assert.Opt[[]StepResultAssertion]
	When             assert.Opt[v1.StepWhenExpressions]
}

// IsAssertable marks StepAssertion as an Assertable.
func (_ StepAssertion) IsAssertable() {}

// StepOutputConfigAssertion is the assertion struct for StepOutputConfig.
type StepOutputConfigAssertion struct {
	Path assert.Opt[string]
}

// IsAssertable marks StepOutputConfigAssertion as an Assertable.
func (_ StepOutputConfigAssertion) IsAssertable() {}

// StepResultAssertion is the assertion struct for StepResult.
type StepResultAssertion struct {
	Name        assert.Opt[string]
	Type        assert.Opt[v1.ResultsType]
	Properties  assert.Opt[map[string]v1.PropertySpec]
	Description assert.Opt[string]
}

// IsAssertable marks StepResultAssertion as an Assertable.
func (_ StepResultAssertion) IsAssertable() {}

// StepStateAssertion is the assertion struct for StepState.
type StepStateAssertion struct {
	ContainerState    assert.Opt[v12.ContainerState]
	Name              assert.Opt[string]
	Container         assert.Opt[string]
	ImageID           assert.Opt[string]
	Results           assert.Opt[[]v1.TaskRunStepResult]
	Provenance        ProvenanceAssertion
	TerminationReason assert.Opt[string]
	Inputs            assert.Opt[[]v1.TaskRunStepArtifact]
	Outputs           assert.Opt[[]v1.TaskRunStepArtifact]
}

// IsAssertable marks StepStateAssertion as an Assertable.
func (_ StepStateAssertion) IsAssertable() {}

// StepTemplateAssertion is the assertion struct for StepTemplate.
type StepTemplateAssertion struct {
	Image            assert.Opt[string]
	Command          assert.Opt[[]string]
	Args             assert.Opt[[]string]
	WorkingDir       assert.Opt[string]
	EnvFrom          assert.Opt[[]v12.EnvFromSource]
	Env              assert.Opt[[]v12.EnvVar]
	ComputeResources assert.Opt[v12.ResourceRequirements]
	VolumeMounts     assert.Opt[[]v12.VolumeMount]
	VolumeDevices    assert.Opt[[]v12.VolumeDevice]
	ImagePullPolicy  assert.Opt[v12.PullPolicy]
	SecurityContext  assert.Opt[*v12.SecurityContext]
}

// IsAssertable marks StepTemplateAssertion as an Assertable.
func (_ StepTemplateAssertion) IsAssertable() {}

// TaskAssertion is the assertion struct for Task.
type TaskAssertion struct {
	TypeMeta   assert.Opt[v11.TypeMeta]
	ObjectMeta assert.Opt[v11.ObjectMeta]
	Spec       TaskSpecAssertion
}

// IsAssertable marks TaskAssertion as an Assertable.
func (_ TaskAssertion) IsAssertable() {}

// TaskBreakpointsAssertion is the assertion struct for TaskBreakpoints.
type TaskBreakpointsAssertion struct {
	OnFailure   assert.Opt[string]
	BeforeSteps assert.Opt[[]string]
}

// IsAssertable marks TaskBreakpointsAssertion as an Assertable.
func (_ TaskBreakpointsAssertion) IsAssertable() {}

// TaskRefAssertion is the assertion struct for TaskRef.
type TaskRefAssertion struct {
	Name        assert.Opt[string]
	Kind        assert.Opt[v1.TaskKind]
	APIVersion  assert.Opt[string]
	ResolverRef ResolverRefAssertion
}

// IsAssertable marks TaskRefAssertion as an Assertable.
func (_ TaskRefAssertion) IsAssertable() {}

// TaskResultAssertion is the assertion struct for TaskResult.
type TaskResultAssertion struct {
	Name        assert.Opt[string]
	Type        assert.Opt[v1.ResultsType]
	Properties  assert.Opt[map[string]v1.PropertySpec]
	Description assert.Opt[string]
	Value       assert.Opt[*v1.ResultValue]
}

// IsAssertable marks TaskResultAssertion as an Assertable.
func (_ TaskResultAssertion) IsAssertable() {}

// TaskRunAssertion is the assertion struct for TaskRun.
type TaskRunAssertion struct {
	TypeMeta   assert.Opt[v11.TypeMeta]
	ObjectMeta assert.Opt[v11.ObjectMeta]
	Spec       TaskRunSpecAssertion
	Status     assert.Opt[v1.TaskRunStatus]
}

// IsAssertable marks TaskRunAssertion as an Assertable.
func (_ TaskRunAssertion) IsAssertable() {}

// TaskRunDebugAssertion is the assertion struct for TaskRunDebug.
type TaskRunDebugAssertion struct {
	Breakpoints TaskBreakpointsAssertion
}

// IsAssertable marks TaskRunDebugAssertion as an Assertable.
func (_ TaskRunDebugAssertion) IsAssertable() {}

// TaskRunInputsAssertion is the assertion struct for TaskRunInputs.
type TaskRunInputsAssertion struct {
	Params assert.Opt[v1.Params]
}

// IsAssertable marks TaskRunInputsAssertion as an Assertable.
func (_ TaskRunInputsAssertion) IsAssertable() {}

// TaskRunResultAssertion is the assertion struct for TaskRunResult.
type TaskRunResultAssertion struct {
	Name  assert.Opt[string]
	Type  assert.Opt[v1.ResultsType]
	Value assert.Opt[v1.ResultValue]
}

// IsAssertable marks TaskRunResultAssertion as an Assertable.
func (_ TaskRunResultAssertion) IsAssertable() {}

// TaskRunSidecarSpecAssertion is the assertion struct for TaskRunSidecarSpec.
type TaskRunSidecarSpecAssertion struct {
	Name             assert.Opt[string]
	ComputeResources assert.Opt[v12.ResourceRequirements]
}

// IsAssertable marks TaskRunSidecarSpecAssertion as an Assertable.
func (_ TaskRunSidecarSpecAssertion) IsAssertable() {}

// TaskRunSpecAssertion is the assertion struct for TaskRunSpec.
type TaskRunSpecAssertion struct {
	Debug              TaskRunDebugAssertion
	Params             assert.Opt[v1.Params]
	ServiceAccountName assert.Opt[string]
	TaskRef            TaskRefAssertion
	TaskSpec           TaskSpecAssertion
	Status             assert.Opt[v1.TaskRunSpecStatus]
	StatusMessage      assert.Opt[v1.TaskRunSpecStatusMessage]
	Retries            assert.Opt[int]
	Timeout            assert.Opt[*v11.Duration]
	PodTemplate        assert.Opt[*pod.PodTemplate]
	Workspaces         assert.Opt[[]WorkspaceBindingAssertion]
	StepSpecs          assert.Opt[[]TaskRunStepSpecAssertion]
	SidecarSpecs       assert.Opt[[]TaskRunSidecarSpecAssertion]
	ComputeResources   assert.Opt[*v12.ResourceRequirements]
	ManagedBy          assert.Opt[*string]
}

// IsAssertable marks TaskRunSpecAssertion as an Assertable.
func (_ TaskRunSpecAssertion) IsAssertable() {}

// TaskRunStatusFieldsAssertion is the assertion struct for TaskRunStatusFields.
type TaskRunStatusFieldsAssertion struct {
	PodName        assert.Opt[string]
	StartTime      assert.Opt[*v11.Time]
	CompletionTime assert.Opt[*v11.Time]
	Steps          assert.Opt[[]StepStateAssertion]
	RetriesStatus  assert.Opt[v1.RetriesStatus]
	Results        assert.Opt[[]TaskRunResultAssertion]
	Artifacts      ArtifactsAssertion
	Sidecars       assert.Opt[[]SidecarStateAssertion]
	TaskSpec       TaskSpecAssertion
	Provenance     ProvenanceAssertion
	SpanContext    assert.Opt[map[string]string]
}

// IsAssertable marks TaskRunStatusFieldsAssertion as an Assertable.
func (_ TaskRunStatusFieldsAssertion) IsAssertable() {}

// TaskRunStepSpecAssertion is the assertion struct for TaskRunStepSpec.
type TaskRunStepSpecAssertion struct {
	Name             assert.Opt[string]
	ComputeResources assert.Opt[v12.ResourceRequirements]
}

// IsAssertable marks TaskRunStepSpecAssertion as an Assertable.
func (_ TaskRunStepSpecAssertion) IsAssertable() {}

// TaskSpecAssertion is the assertion struct for TaskSpec.
type TaskSpecAssertion struct {
	Params       assert.Opt[v1.ParamSpecs]
	DisplayName  assert.Opt[string]
	Description  assert.Opt[string]
	Steps        assert.Opt[[]StepAssertion]
	Volumes      assert.Opt[v1.Volumes]
	StepTemplate StepTemplateAssertion
	Sidecars     assert.Opt[[]SidecarAssertion]
	Workspaces   assert.Opt[[]WorkspaceDeclarationAssertion]
	Results      assert.Opt[[]TaskResultAssertion]
}

// IsAssertable marks TaskSpecAssertion as an Assertable.
func (_ TaskSpecAssertion) IsAssertable() {}

// TimeoutFieldsAssertion is the assertion struct for TimeoutFields.
type TimeoutFieldsAssertion struct {
	Pipeline assert.Opt[*v11.Duration]
	Tasks    assert.Opt[*v11.Duration]
	Finally  assert.Opt[*v11.Duration]
}

// IsAssertable marks TimeoutFieldsAssertion as an Assertable.
func (_ TimeoutFieldsAssertion) IsAssertable() {}

// WhenExpressionAssertion is the assertion struct for WhenExpression.
type WhenExpressionAssertion struct {
	Input    assert.Opt[string]
	Operator assert.Opt[selection.Operator]
	Values   assert.Opt[[]string]
	CEL      assert.Opt[string]
}

// IsAssertable marks WhenExpressionAssertion as an Assertable.
func (_ WhenExpressionAssertion) IsAssertable() {}

// WorkspaceBindingAssertion is the assertion struct for WorkspaceBinding.
type WorkspaceBindingAssertion struct {
	Name                  assert.Opt[string]
	SubPath               assert.Opt[string]
	VolumeClaimTemplate   assert.Opt[*v12.PersistentVolumeClaim]
	PersistentVolumeClaim assert.Opt[*v12.PersistentVolumeClaimVolumeSource]
	EmptyDir              assert.Opt[*v12.EmptyDirVolumeSource]
	ConfigMap             assert.Opt[*v12.ConfigMapVolumeSource]
	Secret                assert.Opt[*v12.SecretVolumeSource]
	Projected             assert.Opt[*v12.ProjectedVolumeSource]
	CSI                   assert.Opt[*v12.CSIVolumeSource]
}

// IsAssertable marks WorkspaceBindingAssertion as an Assertable.
func (_ WorkspaceBindingAssertion) IsAssertable() {}

// WorkspaceDeclarationAssertion is the assertion struct for WorkspaceDeclaration.
type WorkspaceDeclarationAssertion struct {
	Name        assert.Opt[string]
	Description assert.Opt[string]
	MountPath   assert.Opt[string]
	ReadOnly    assert.Opt[bool]
	Optional    assert.Opt[bool]
}

// IsAssertable marks WorkspaceDeclarationAssertion as an Assertable.
func (_ WorkspaceDeclarationAssertion) IsAssertable() {}

// WorkspacePipelineTaskBindingAssertion is the assertion struct for WorkspacePipelineTaskBinding.
type WorkspacePipelineTaskBindingAssertion struct {
	Name      assert.Opt[string]
	Workspace assert.Opt[string]
	SubPath   assert.Opt[string]
}

// IsAssertable marks WorkspacePipelineTaskBindingAssertion as an Assertable.
func (_ WorkspacePipelineTaskBindingAssertion) IsAssertable() {}

// WorkspaceUsageAssertion is the assertion struct for WorkspaceUsage.
type WorkspaceUsageAssertion struct {
	Name      assert.Opt[string]
	MountPath assert.Opt[string]
}

// IsAssertable marks WorkspaceUsageAssertion as an Assertable.
func (_ WorkspaceUsageAssertion) IsAssertable() {}
