// Code generated by envgen. DO NOT EDIT.

package v1

import (
	"fmt"
	v1 "github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1"
	assert "github.com/mridang/wilhelm/assert"
	v12 "github.com/mridang/wilhelm/assert/cert/manager/v1"
	env "github.com/mridang/wilhelm/env"
	require "github.com/stretchr/testify/require"
	errors "k8s.io/apimachinery/pkg/api/errors"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	"testing"
)

// GetCertificate fetches a Certificate by name via the dynamic client, failing the test on error.
func GetCertificate(env *env.Env, t *testing.T, name string) *v1.Certificate {
	t.Helper()
	obj, err := GetCertificateE(env, t, name)
	require.NoError(t, err, "failed to get Certificate %s", name)
	return obj
}

// GetCertificateE fetches a Certificate by name via the dynamic client, returning the error for non-existence checks.
func GetCertificateE(env *env.Env, t *testing.T, name string) (*v1.Certificate, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "cert-manager.io",
		Resource: "certificates",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.Certificate
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert Certificate from unstructured: %w", err)
	}
	return &out, nil
}

// AssertCertificate fetches a Certificate and runs a partial assertion against it.
func AssertCertificate(env *env.Env, t *testing.T, name string, asn v12.CertificateAssertion) {
	t.Helper()
	assert.Partial(t, GetCertificate(env, t, name), asn, name)
}

// GetCertificateRequest fetches a CertificateRequest by name via the dynamic client, failing the test on error.
func GetCertificateRequest(env *env.Env, t *testing.T, name string) *v1.CertificateRequest {
	t.Helper()
	obj, err := GetCertificateRequestE(env, t, name)
	require.NoError(t, err, "failed to get CertificateRequest %s", name)
	return obj
}

// GetCertificateRequestE fetches a CertificateRequest by name via the dynamic client, returning the error for non-existence checks.
func GetCertificateRequestE(env *env.Env, t *testing.T, name string) (*v1.CertificateRequest, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "cert-manager.io",
		Resource: "certificaterequests",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.CertificateRequest
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert CertificateRequest from unstructured: %w", err)
	}
	return &out, nil
}

// AssertCertificateRequest fetches a CertificateRequest and runs a partial assertion against it.
func AssertCertificateRequest(env *env.Env, t *testing.T, name string, asn v12.CertificateRequestAssertion) {
	t.Helper()
	assert.Partial(t, GetCertificateRequest(env, t, name), asn, name)
}

// GetClusterIssuer fetches a ClusterIssuer by name via the dynamic client, failing the test on error.
func GetClusterIssuer(env *env.Env, t *testing.T, name string) *v1.ClusterIssuer {
	t.Helper()
	obj, err := GetClusterIssuerE(env, t, name)
	require.NoError(t, err, "failed to get ClusterIssuer %s", name)
	return obj
}

// GetClusterIssuerE fetches a ClusterIssuer by name via the dynamic client, returning the error for non-existence checks.
func GetClusterIssuerE(env *env.Env, t *testing.T, name string) (*v1.ClusterIssuer, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "cert-manager.io",
		Resource: "clusterissuers",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.ClusterIssuer
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert ClusterIssuer from unstructured: %w", err)
	}
	return &out, nil
}

// AssertClusterIssuer fetches a ClusterIssuer and runs a partial assertion against it.
func AssertClusterIssuer(env *env.Env, t *testing.T, name string, asn v12.ClusterIssuerAssertion) {
	t.Helper()
	assert.Partial(t, GetClusterIssuer(env, t, name), asn, name)
}

// GetIssuer fetches a Issuer by name via the dynamic client, failing the test on error.
func GetIssuer(env *env.Env, t *testing.T, name string) *v1.Issuer {
	t.Helper()
	obj, err := GetIssuerE(env, t, name)
	require.NoError(t, err, "failed to get Issuer %s", name)
	return obj
}

// GetIssuerE fetches a Issuer by name via the dynamic client, returning the error for non-existence checks.
func GetIssuerE(env *env.Env, t *testing.T, name string) (*v1.Issuer, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "cert-manager.io",
		Resource: "issuers",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.Issuer
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert Issuer from unstructured: %w", err)
	}
	return &out, nil
}

// AssertIssuer fetches a Issuer and runs a partial assertion against it.
func AssertIssuer(env *env.Env, t *testing.T, name string, asn v12.IssuerAssertion) {
	t.Helper()
	assert.Partial(t, GetIssuer(env, t, name), asn, name)
}

// AssertPartial dispatches assertion to the matching Assert<Kind> based on
// the concrete type of assertion.
func AssertPartial(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch a := assertion.(type) {
	case v12.CertificateAssertion:
		AssertCertificate(env, t, name, a)
	case *v12.CertificateAssertion:
		AssertCertificate(env, t, name, *a)
	case v12.CertificateRequestAssertion:
		AssertCertificateRequest(env, t, name, a)
	case *v12.CertificateRequestAssertion:
		AssertCertificateRequest(env, t, name, *a)
	case v12.ClusterIssuerAssertion:
		AssertClusterIssuer(env, t, name, a)
	case *v12.ClusterIssuerAssertion:
		AssertClusterIssuer(env, t, name, *a)
	case v12.IssuerAssertion:
		AssertIssuer(env, t, name, a)
	case *v12.IssuerAssertion:
		AssertIssuer(env, t, name, *a)
	default:
		t.Fatalf("AssertPartial: no Kind registered for assertion type %T", assertion)
	}
}

// AssertNone asserts that the Kind implied by assertion does not exist
// (the dynamic-client GET returns NotFound).
func AssertNone(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch assertion.(type) {
	case v12.CertificateAssertion, *v12.CertificateAssertion:
		_, err := GetCertificateE(env, t, name)
		require.True(t, errors.IsNotFound(err), "Certificate %q should not exist (err: %v)", name, err)
	case v12.CertificateRequestAssertion, *v12.CertificateRequestAssertion:
		_, err := GetCertificateRequestE(env, t, name)
		require.True(t, errors.IsNotFound(err), "CertificateRequest %q should not exist (err: %v)", name, err)
	case v12.ClusterIssuerAssertion, *v12.ClusterIssuerAssertion:
		_, err := GetClusterIssuerE(env, t, name)
		require.True(t, errors.IsNotFound(err), "ClusterIssuer %q should not exist (err: %v)", name, err)
	case v12.IssuerAssertion, *v12.IssuerAssertion:
		_, err := GetIssuerE(env, t, name)
		require.True(t, errors.IsNotFound(err), "Issuer %q should not exist (err: %v)", name, err)
	default:
		t.Fatalf("AssertNone: no Kind registered for assertion type %T", assertion)
	}
}
