// Code generated by assertgen. DO NOT EDIT.

package v1

import (
	assert "github.com/mridang/wilhelm/assert"
	v11 "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
	v12 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// BackupAssertion is the assertion struct for Backup.
type BackupAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       BackupSpecAssertion
	Status     assert.Opt[v11.BackupStatus]
}

// IsAssertable marks BackupAssertion as an Assertable.
func (_ BackupAssertion) IsAssertable() {}

// BackupHooksAssertion is the assertion struct for BackupHooks.
type BackupHooksAssertion struct {
	Resources assert.Opt[[]BackupResourceHookSpecAssertion]
}

// IsAssertable marks BackupHooksAssertion as an Assertable.
func (_ BackupHooksAssertion) IsAssertable() {}

// BackupProgressAssertion is the assertion struct for BackupProgress.
type BackupProgressAssertion struct {
	TotalItems    assert.Opt[int]
	ItemsBackedUp assert.Opt[int]
}

// IsAssertable marks BackupProgressAssertion as an Assertable.
func (_ BackupProgressAssertion) IsAssertable() {}

// BackupRepositoryAssertion is the assertion struct for BackupRepository.
type BackupRepositoryAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       BackupRepositorySpecAssertion
	Status     assert.Opt[v11.BackupRepositoryStatus]
}

// IsAssertable marks BackupRepositoryAssertion as an Assertable.
func (_ BackupRepositoryAssertion) IsAssertable() {}

// BackupRepositorySpecAssertion is the assertion struct for BackupRepositorySpec.
type BackupRepositorySpecAssertion struct {
	VolumeNamespace       assert.Opt[string]
	BackupStorageLocation assert.Opt[string]
	RepositoryType        assert.Opt[string]
	ResticIdentifier      assert.Opt[string]
	MaintenanceFrequency  assert.Opt[v1.Duration]
	RepositoryConfig      assert.Opt[map[string]string]
}

// IsAssertable marks BackupRepositorySpecAssertion as an Assertable.
func (_ BackupRepositorySpecAssertion) IsAssertable() {}

// BackupResourceHookAssertion is the assertion struct for BackupResourceHook.
type BackupResourceHookAssertion struct {
	Exec ExecHookAssertion
}

// IsAssertable marks BackupResourceHookAssertion as an Assertable.
func (_ BackupResourceHookAssertion) IsAssertable() {}

// BackupResourceHookSpecAssertion is the assertion struct for BackupResourceHookSpec.
type BackupResourceHookSpecAssertion struct {
	Name               assert.Opt[string]
	IncludedNamespaces assert.Opt[[]string]
	ExcludedNamespaces assert.Opt[[]string]
	IncludedResources  assert.Opt[[]string]
	ExcludedResources  assert.Opt[[]string]
	LabelSelector      assert.Opt[*v1.LabelSelector]
	PreHooks           assert.Opt[[]BackupResourceHookAssertion]
	PostHooks          assert.Opt[[]BackupResourceHookAssertion]
}

// IsAssertable marks BackupResourceHookSpecAssertion as an Assertable.
func (_ BackupResourceHookSpecAssertion) IsAssertable() {}

// BackupSpecAssertion is the assertion struct for BackupSpec.
type BackupSpecAssertion struct {
	Metadata                         MetadataAssertion
	IncludedNamespaces               assert.Opt[[]string]
	ExcludedNamespaces               assert.Opt[[]string]
	IncludedResources                assert.Opt[[]string]
	ExcludedResources                assert.Opt[[]string]
	IncludedClusterScopedResources   assert.Opt[[]string]
	ExcludedClusterScopedResources   assert.Opt[[]string]
	IncludedNamespaceScopedResources assert.Opt[[]string]
	ExcludedNamespaceScopedResources assert.Opt[[]string]
	LabelSelector                    assert.Opt[*v1.LabelSelector]
	OrLabelSelectors                 assert.Opt[[]*v1.LabelSelector]
	SnapshotVolumes                  assert.Opt[*bool]
	TTL                              assert.Opt[v1.Duration]
	VolumeGroupSnapshotLabelKey      assert.Opt[string]
	IncludeClusterResources          assert.Opt[*bool]
	Hooks                            BackupHooksAssertion
	StorageLocation                  assert.Opt[string]
	VolumeSnapshotLocations          assert.Opt[[]string]
	DefaultVolumesToRestic           assert.Opt[*bool]
	DefaultVolumesToFsBackup         assert.Opt[*bool]
	OrderedResources                 assert.Opt[map[string]string]
	CSISnapshotTimeout               assert.Opt[v1.Duration]
	ItemOperationTimeout             assert.Opt[v1.Duration]
	ResourcePolicy                   assert.Opt[*v12.TypedLocalObjectReference]
	SnapshotMoveData                 assert.Opt[*bool]
	DataMover                        assert.Opt[string]
	UploaderConfig                   UploaderConfigForBackupAssertion
}

// IsAssertable marks BackupSpecAssertion as an Assertable.
func (_ BackupSpecAssertion) IsAssertable() {}

// BackupStorageLocationAssertion is the assertion struct for BackupStorageLocation.
type BackupStorageLocationAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       BackupStorageLocationSpecAssertion
	Status     assert.Opt[v11.BackupStorageLocationStatus]
}

// IsAssertable marks BackupStorageLocationAssertion as an Assertable.
func (_ BackupStorageLocationAssertion) IsAssertable() {}

// BackupStorageLocationSpecAssertion is the assertion struct for BackupStorageLocationSpec.
type BackupStorageLocationSpecAssertion struct {
	Provider            assert.Opt[string]
	Config              assert.Opt[map[string]string]
	Credential          assert.Opt[*v12.SecretKeySelector]
	StorageType         StorageTypeAssertion
	Default             assert.Opt[bool]
	AccessMode          assert.Opt[v11.BackupStorageLocationAccessMode]
	BackupSyncPeriod    assert.Opt[*v1.Duration]
	ValidationFrequency assert.Opt[*v1.Duration]
}

// IsAssertable marks BackupStorageLocationSpecAssertion as an Assertable.
func (_ BackupStorageLocationSpecAssertion) IsAssertable() {}

// DeleteBackupRequestAssertion is the assertion struct for DeleteBackupRequest.
type DeleteBackupRequestAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       DeleteBackupRequestSpecAssertion
	Status     assert.Opt[v11.DeleteBackupRequestStatus]
}

// IsAssertable marks DeleteBackupRequestAssertion as an Assertable.
func (_ DeleteBackupRequestAssertion) IsAssertable() {}

// DeleteBackupRequestSpecAssertion is the assertion struct for DeleteBackupRequestSpec.
type DeleteBackupRequestSpecAssertion struct {
	BackupName assert.Opt[string]
}

// IsAssertable marks DeleteBackupRequestSpecAssertion as an Assertable.
func (_ DeleteBackupRequestSpecAssertion) IsAssertable() {}

// DownloadRequestAssertion is the assertion struct for DownloadRequest.
type DownloadRequestAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       DownloadRequestSpecAssertion
	Status     assert.Opt[v11.DownloadRequestStatus]
}

// IsAssertable marks DownloadRequestAssertion as an Assertable.
func (_ DownloadRequestAssertion) IsAssertable() {}

// DownloadRequestSpecAssertion is the assertion struct for DownloadRequestSpec.
type DownloadRequestSpecAssertion struct {
	Target DownloadTargetAssertion
}

// IsAssertable marks DownloadRequestSpecAssertion as an Assertable.
func (_ DownloadRequestSpecAssertion) IsAssertable() {}

// DownloadTargetAssertion is the assertion struct for DownloadTarget.
type DownloadTargetAssertion struct {
	Kind assert.Opt[v11.DownloadTargetKind]
	Name assert.Opt[string]
}

// IsAssertable marks DownloadTargetAssertion as an Assertable.
func (_ DownloadTargetAssertion) IsAssertable() {}

// ExecHookAssertion is the assertion struct for ExecHook.
type ExecHookAssertion struct {
	Container assert.Opt[string]
	Command   assert.Opt[[]string]
	OnError   assert.Opt[v11.HookErrorMode]
	Timeout   assert.Opt[v1.Duration]
}

// IsAssertable marks ExecHookAssertion as an Assertable.
func (_ ExecHookAssertion) IsAssertable() {}

// ExecRestoreHookAssertion is the assertion struct for ExecRestoreHook.
type ExecRestoreHookAssertion struct {
	Container    assert.Opt[string]
	Command      assert.Opt[[]string]
	OnError      assert.Opt[v11.HookErrorMode]
	ExecTimeout  assert.Opt[v1.Duration]
	WaitTimeout  assert.Opt[v1.Duration]
	WaitForReady assert.Opt[*bool]
}

// IsAssertable marks ExecRestoreHookAssertion as an Assertable.
func (_ ExecRestoreHookAssertion) IsAssertable() {}

// InitRestoreHookAssertion is the assertion struct for InitRestoreHook.
type InitRestoreHookAssertion struct {
	InitContainers assert.Opt[[]runtime.RawExtension]
	Timeout        assert.Opt[v1.Duration]
}

// IsAssertable marks InitRestoreHookAssertion as an Assertable.
func (_ InitRestoreHookAssertion) IsAssertable() {}

// MetadataAssertion is the assertion struct for Metadata.
type MetadataAssertion struct {
	Labels assert.Opt[map[string]string]
}

// IsAssertable marks MetadataAssertion as an Assertable.
func (_ MetadataAssertion) IsAssertable() {}

// ObjectStorageLocationAssertion is the assertion struct for ObjectStorageLocation.
type ObjectStorageLocationAssertion struct {
	Bucket    assert.Opt[string]
	Prefix    assert.Opt[string]
	CACert    assert.Opt[[]byte]
	CACertRef assert.Opt[*v12.SecretKeySelector]
}

// IsAssertable marks ObjectStorageLocationAssertion as an Assertable.
func (_ ObjectStorageLocationAssertion) IsAssertable() {}

// PluginInfoAssertion is the assertion struct for PluginInfo.
type PluginInfoAssertion struct {
	Name assert.Opt[string]
	Kind assert.Opt[string]
}

// IsAssertable marks PluginInfoAssertion as an Assertable.
func (_ PluginInfoAssertion) IsAssertable() {}

// PodVolumeBackupAssertion is the assertion struct for PodVolumeBackup.
type PodVolumeBackupAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       PodVolumeBackupSpecAssertion
	Status     assert.Opt[v11.PodVolumeBackupStatus]
}

// IsAssertable marks PodVolumeBackupAssertion as an Assertable.
func (_ PodVolumeBackupAssertion) IsAssertable() {}

// PodVolumeBackupSpecAssertion is the assertion struct for PodVolumeBackupSpec.
type PodVolumeBackupSpecAssertion struct {
	Node                  assert.Opt[string]
	Pod                   assert.Opt[v12.ObjectReference]
	Volume                assert.Opt[string]
	BackupStorageLocation assert.Opt[string]
	RepoIdentifier        assert.Opt[string]
	UploaderType          assert.Opt[string]
	Tags                  assert.Opt[map[string]string]
	UploaderSettings      assert.Opt[map[string]string]
	Cancel                assert.Opt[bool]
}

// IsAssertable marks PodVolumeBackupSpecAssertion as an Assertable.
func (_ PodVolumeBackupSpecAssertion) IsAssertable() {}

// PodVolumeRestoreAssertion is the assertion struct for PodVolumeRestore.
type PodVolumeRestoreAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       PodVolumeRestoreSpecAssertion
	Status     assert.Opt[v11.PodVolumeRestoreStatus]
}

// IsAssertable marks PodVolumeRestoreAssertion as an Assertable.
func (_ PodVolumeRestoreAssertion) IsAssertable() {}

// PodVolumeRestoreSpecAssertion is the assertion struct for PodVolumeRestoreSpec.
type PodVolumeRestoreSpecAssertion struct {
	Pod                   assert.Opt[v12.ObjectReference]
	Volume                assert.Opt[string]
	BackupStorageLocation assert.Opt[string]
	RepoIdentifier        assert.Opt[string]
	UploaderType          assert.Opt[string]
	SnapshotID            assert.Opt[string]
	SourceNamespace       assert.Opt[string]
	UploaderSettings      assert.Opt[map[string]string]
	Cancel                assert.Opt[bool]
	SnapshotSize          assert.Opt[int64]
}

// IsAssertable marks PodVolumeRestoreSpecAssertion as an Assertable.
func (_ PodVolumeRestoreSpecAssertion) IsAssertable() {}

// RestoreAssertion is the assertion struct for Restore.
type RestoreAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       RestoreSpecAssertion
	Status     assert.Opt[v11.RestoreStatus]
}

// IsAssertable marks RestoreAssertion as an Assertable.
func (_ RestoreAssertion) IsAssertable() {}

// RestoreHooksAssertion is the assertion struct for RestoreHooks.
type RestoreHooksAssertion struct {
	Resources assert.Opt[[]RestoreResourceHookSpecAssertion]
}

// IsAssertable marks RestoreHooksAssertion as an Assertable.
func (_ RestoreHooksAssertion) IsAssertable() {}

// RestoreProgressAssertion is the assertion struct for RestoreProgress.
type RestoreProgressAssertion struct {
	TotalItems    assert.Opt[int]
	ItemsRestored assert.Opt[int]
}

// IsAssertable marks RestoreProgressAssertion as an Assertable.
func (_ RestoreProgressAssertion) IsAssertable() {}

// RestoreResourceHookAssertion is the assertion struct for RestoreResourceHook.
type RestoreResourceHookAssertion struct {
	Exec ExecRestoreHookAssertion
	Init InitRestoreHookAssertion
}

// IsAssertable marks RestoreResourceHookAssertion as an Assertable.
func (_ RestoreResourceHookAssertion) IsAssertable() {}

// RestoreResourceHookSpecAssertion is the assertion struct for RestoreResourceHookSpec.
type RestoreResourceHookSpecAssertion struct {
	Name               assert.Opt[string]
	IncludedNamespaces assert.Opt[[]string]
	ExcludedNamespaces assert.Opt[[]string]
	IncludedResources  assert.Opt[[]string]
	ExcludedResources  assert.Opt[[]string]
	LabelSelector      assert.Opt[*v1.LabelSelector]
	PostHooks          assert.Opt[[]RestoreResourceHookAssertion]
}

// IsAssertable marks RestoreResourceHookSpecAssertion as an Assertable.
func (_ RestoreResourceHookSpecAssertion) IsAssertable() {}

// RestoreSpecAssertion is the assertion struct for RestoreSpec.
type RestoreSpecAssertion struct {
	BackupName              assert.Opt[string]
	ScheduleName            assert.Opt[string]
	IncludedNamespaces      assert.Opt[[]string]
	ExcludedNamespaces      assert.Opt[[]string]
	IncludedResources       assert.Opt[[]string]
	ExcludedResources       assert.Opt[[]string]
	NamespaceMapping        assert.Opt[map[string]string]
	LabelSelector           assert.Opt[*v1.LabelSelector]
	OrLabelSelectors        assert.Opt[[]*v1.LabelSelector]
	RestorePVs              assert.Opt[*bool]
	RestoreStatus           RestoreStatusSpecAssertion
	PreserveNodePorts       assert.Opt[*bool]
	IncludeClusterResources assert.Opt[*bool]
	Hooks                   RestoreHooksAssertion
	ExistingResourcePolicy  assert.Opt[v11.PolicyType]
	ItemOperationTimeout    assert.Opt[v1.Duration]
	ResourceModifier        assert.Opt[*v12.TypedLocalObjectReference]
	UploaderConfig          UploaderConfigForRestoreAssertion
}

// IsAssertable marks RestoreSpecAssertion as an Assertable.
func (_ RestoreSpecAssertion) IsAssertable() {}

// RestoreStatusSpecAssertion is the assertion struct for RestoreStatusSpec.
type RestoreStatusSpecAssertion struct {
	IncludedResources assert.Opt[[]string]
	ExcludedResources assert.Opt[[]string]
}

// IsAssertable marks RestoreStatusSpecAssertion as an Assertable.
func (_ RestoreStatusSpecAssertion) IsAssertable() {}

// ScheduleAssertion is the assertion struct for Schedule.
type ScheduleAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       ScheduleSpecAssertion
	Status     assert.Opt[v11.ScheduleStatus]
}

// IsAssertable marks ScheduleAssertion as an Assertable.
func (_ ScheduleAssertion) IsAssertable() {}

// ScheduleSpecAssertion is the assertion struct for ScheduleSpec.
type ScheduleSpecAssertion struct {
	Template                   BackupSpecAssertion
	Schedule                   assert.Opt[string]
	UseOwnerReferencesInBackup assert.Opt[*bool]
	Paused                     assert.Opt[bool]
	SkipImmediately            assert.Opt[*bool]
}

// IsAssertable marks ScheduleSpecAssertion as an Assertable.
func (_ ScheduleSpecAssertion) IsAssertable() {}

// SchemeGroupVersionAssertion is the assertion struct for GroupVersion.
type SchemeGroupVersionAssertion struct {
	Group   assert.Opt[string]
	Version assert.Opt[string]
}

// IsAssertable marks SchemeGroupVersionAssertion as an Assertable.
func (_ SchemeGroupVersionAssertion) IsAssertable() {}

// ServerStatusRequestAssertion is the assertion struct for ServerStatusRequest.
type ServerStatusRequestAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       ServerStatusRequestSpecAssertion
	Status     assert.Opt[v11.ServerStatusRequestStatus]
}

// IsAssertable marks ServerStatusRequestAssertion as an Assertable.
func (_ ServerStatusRequestAssertion) IsAssertable() {}

// ServerStatusRequestSpecAssertion is the assertion struct for ServerStatusRequestSpec.
type ServerStatusRequestSpecAssertion struct{}

// IsAssertable marks ServerStatusRequestSpecAssertion as an Assertable.
func (_ ServerStatusRequestSpecAssertion) IsAssertable() {}

// StorageTypeAssertion is the assertion struct for StorageType.
type StorageTypeAssertion struct {
	ObjectStorage ObjectStorageLocationAssertion
}

// IsAssertable marks StorageTypeAssertion as an Assertable.
func (_ StorageTypeAssertion) IsAssertable() {}

// UploaderConfigForBackupAssertion is the assertion struct for UploaderConfigForBackup.
type UploaderConfigForBackupAssertion struct {
	ParallelFilesUpload assert.Opt[int]
}

// IsAssertable marks UploaderConfigForBackupAssertion as an Assertable.
func (_ UploaderConfigForBackupAssertion) IsAssertable() {}

// UploaderConfigForRestoreAssertion is the assertion struct for UploaderConfigForRestore.
type UploaderConfigForRestoreAssertion struct {
	WriteSparseFiles      assert.Opt[*bool]
	ParallelFilesDownload assert.Opt[int]
}

// IsAssertable marks UploaderConfigForRestoreAssertion as an Assertable.
func (_ UploaderConfigForRestoreAssertion) IsAssertable() {}

// VolumeSnapshotLocationAssertion is the assertion struct for VolumeSnapshotLocation.
type VolumeSnapshotLocationAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       VolumeSnapshotLocationSpecAssertion
	Status     assert.Opt[v11.VolumeSnapshotLocationStatus]
}

// IsAssertable marks VolumeSnapshotLocationAssertion as an Assertable.
func (_ VolumeSnapshotLocationAssertion) IsAssertable() {}

// VolumeSnapshotLocationSpecAssertion is the assertion struct for VolumeSnapshotLocationSpec.
type VolumeSnapshotLocationSpecAssertion struct {
	Provider   assert.Opt[string]
	Config     assert.Opt[map[string]string]
	Credential assert.Opt[*v12.SecretKeySelector]
}

// IsAssertable marks VolumeSnapshotLocationSpecAssertion as an Assertable.
func (_ VolumeSnapshotLocationSpecAssertion) IsAssertable() {}
