// Code generated by envgen. DO NOT EDIT.

package v1

import (
	"fmt"
	v1 "github.com/fluxcd/source-controller/api/v1"
	assert "github.com/mridang/wilhelm/assert"
	v12 "github.com/mridang/wilhelm/assert/flux/source/v1"
	env "github.com/mridang/wilhelm/env"
	require "github.com/stretchr/testify/require"
	errors "k8s.io/apimachinery/pkg/api/errors"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	"testing"
)

// GetBucket fetches a Bucket by name via the dynamic client, failing the test on error.
func GetBucket(env *env.Env, t *testing.T, name string) *v1.Bucket {
	t.Helper()
	obj, err := GetBucketE(env, t, name)
	require.NoError(t, err, "failed to get Bucket %s", name)
	return obj
}

// GetBucketE fetches a Bucket by name via the dynamic client, returning the error for non-existence checks.
func GetBucketE(env *env.Env, t *testing.T, name string) (*v1.Bucket, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "source.toolkit.fluxcd.io",
		Resource: "buckets",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.Bucket
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert Bucket from unstructured: %w", err)
	}
	return &out, nil
}

// AssertBucket fetches a Bucket and runs a partial assertion against it.
func AssertBucket(env *env.Env, t *testing.T, name string, asn v12.BucketAssertion) {
	t.Helper()
	assert.Partial(t, GetBucket(env, t, name), asn, name)
}

// GetExternalArtifact fetches a ExternalArtifact by name via the dynamic client, failing the test on error.
func GetExternalArtifact(env *env.Env, t *testing.T, name string) *v1.ExternalArtifact {
	t.Helper()
	obj, err := GetExternalArtifactE(env, t, name)
	require.NoError(t, err, "failed to get ExternalArtifact %s", name)
	return obj
}

// GetExternalArtifactE fetches a ExternalArtifact by name via the dynamic client, returning the error for non-existence checks.
func GetExternalArtifactE(env *env.Env, t *testing.T, name string) (*v1.ExternalArtifact, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "source.toolkit.fluxcd.io",
		Resource: "externalartifacts",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.ExternalArtifact
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert ExternalArtifact from unstructured: %w", err)
	}
	return &out, nil
}

// AssertExternalArtifact fetches a ExternalArtifact and runs a partial assertion against it.
func AssertExternalArtifact(env *env.Env, t *testing.T, name string, asn v12.ExternalArtifactAssertion) {
	t.Helper()
	assert.Partial(t, GetExternalArtifact(env, t, name), asn, name)
}

// GetGitRepository fetches a GitRepository by name via the dynamic client, failing the test on error.
func GetGitRepository(env *env.Env, t *testing.T, name string) *v1.GitRepository {
	t.Helper()
	obj, err := GetGitRepositoryE(env, t, name)
	require.NoError(t, err, "failed to get GitRepository %s", name)
	return obj
}

// GetGitRepositoryE fetches a GitRepository by name via the dynamic client, returning the error for non-existence checks.
func GetGitRepositoryE(env *env.Env, t *testing.T, name string) (*v1.GitRepository, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "source.toolkit.fluxcd.io",
		Resource: "gitrepositories",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.GitRepository
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert GitRepository from unstructured: %w", err)
	}
	return &out, nil
}

// AssertGitRepository fetches a GitRepository and runs a partial assertion against it.
func AssertGitRepository(env *env.Env, t *testing.T, name string, asn v12.GitRepositoryAssertion) {
	t.Helper()
	assert.Partial(t, GetGitRepository(env, t, name), asn, name)
}

// GetHelmChart fetches a HelmChart by name via the dynamic client, failing the test on error.
func GetHelmChart(env *env.Env, t *testing.T, name string) *v1.HelmChart {
	t.Helper()
	obj, err := GetHelmChartE(env, t, name)
	require.NoError(t, err, "failed to get HelmChart %s", name)
	return obj
}

// GetHelmChartE fetches a HelmChart by name via the dynamic client, returning the error for non-existence checks.
func GetHelmChartE(env *env.Env, t *testing.T, name string) (*v1.HelmChart, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "source.toolkit.fluxcd.io",
		Resource: "helmcharts",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.HelmChart
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert HelmChart from unstructured: %w", err)
	}
	return &out, nil
}

// AssertHelmChart fetches a HelmChart and runs a partial assertion against it.
func AssertHelmChart(env *env.Env, t *testing.T, name string, asn v12.HelmChartAssertion) {
	t.Helper()
	assert.Partial(t, GetHelmChart(env, t, name), asn, name)
}

// GetHelmRepository fetches a HelmRepository by name via the dynamic client, failing the test on error.
func GetHelmRepository(env *env.Env, t *testing.T, name string) *v1.HelmRepository {
	t.Helper()
	obj, err := GetHelmRepositoryE(env, t, name)
	require.NoError(t, err, "failed to get HelmRepository %s", name)
	return obj
}

// GetHelmRepositoryE fetches a HelmRepository by name via the dynamic client, returning the error for non-existence checks.
func GetHelmRepositoryE(env *env.Env, t *testing.T, name string) (*v1.HelmRepository, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "source.toolkit.fluxcd.io",
		Resource: "helmrepositories",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.HelmRepository
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert HelmRepository from unstructured: %w", err)
	}
	return &out, nil
}

// AssertHelmRepository fetches a HelmRepository and runs a partial assertion against it.
func AssertHelmRepository(env *env.Env, t *testing.T, name string, asn v12.HelmRepositoryAssertion) {
	t.Helper()
	assert.Partial(t, GetHelmRepository(env, t, name), asn, name)
}

// GetOCIRepository fetches a OCIRepository by name via the dynamic client, failing the test on error.
func GetOCIRepository(env *env.Env, t *testing.T, name string) *v1.OCIRepository {
	t.Helper()
	obj, err := GetOCIRepositoryE(env, t, name)
	require.NoError(t, err, "failed to get OCIRepository %s", name)
	return obj
}

// GetOCIRepositoryE fetches a OCIRepository by name via the dynamic client, returning the error for non-existence checks.
func GetOCIRepositoryE(env *env.Env, t *testing.T, name string) (*v1.OCIRepository, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "source.toolkit.fluxcd.io",
		Resource: "ocirepositories",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.OCIRepository
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert OCIRepository from unstructured: %w", err)
	}
	return &out, nil
}

// AssertOCIRepository fetches a OCIRepository and runs a partial assertion against it.
func AssertOCIRepository(env *env.Env, t *testing.T, name string, asn v12.OCIRepositoryAssertion) {
	t.Helper()
	assert.Partial(t, GetOCIRepository(env, t, name), asn, name)
}

// AssertPartial dispatches assertion to the matching Assert<Kind> based on
// the concrete type of assertion.
func AssertPartial(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch a := assertion.(type) {
	case v12.BucketAssertion:
		AssertBucket(env, t, name, a)
	case *v12.BucketAssertion:
		AssertBucket(env, t, name, *a)
	case v12.ExternalArtifactAssertion:
		AssertExternalArtifact(env, t, name, a)
	case *v12.ExternalArtifactAssertion:
		AssertExternalArtifact(env, t, name, *a)
	case v12.GitRepositoryAssertion:
		AssertGitRepository(env, t, name, a)
	case *v12.GitRepositoryAssertion:
		AssertGitRepository(env, t, name, *a)
	case v12.HelmChartAssertion:
		AssertHelmChart(env, t, name, a)
	case *v12.HelmChartAssertion:
		AssertHelmChart(env, t, name, *a)
	case v12.HelmRepositoryAssertion:
		AssertHelmRepository(env, t, name, a)
	case *v12.HelmRepositoryAssertion:
		AssertHelmRepository(env, t, name, *a)
	case v12.OCIRepositoryAssertion:
		AssertOCIRepository(env, t, name, a)
	case *v12.OCIRepositoryAssertion:
		AssertOCIRepository(env, t, name, *a)
	default:
		t.Fatalf("AssertPartial: no Kind registered for assertion type %T", assertion)
	}
}

// AssertNone asserts that the Kind implied by assertion does not exist
// (the dynamic-client GET returns NotFound).
func AssertNone(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch assertion.(type) {
	case v12.BucketAssertion, *v12.BucketAssertion:
		_, err := GetBucketE(env, t, name)
		require.True(t, errors.IsNotFound(err), "Bucket %q should not exist (err: %v)", name, err)
	case v12.ExternalArtifactAssertion, *v12.ExternalArtifactAssertion:
		_, err := GetExternalArtifactE(env, t, name)
		require.True(t, errors.IsNotFound(err), "ExternalArtifact %q should not exist (err: %v)", name, err)
	case v12.GitRepositoryAssertion, *v12.GitRepositoryAssertion:
		_, err := GetGitRepositoryE(env, t, name)
		require.True(t, errors.IsNotFound(err), "GitRepository %q should not exist (err: %v)", name, err)
	case v12.HelmChartAssertion, *v12.HelmChartAssertion:
		_, err := GetHelmChartE(env, t, name)
		require.True(t, errors.IsNotFound(err), "HelmChart %q should not exist (err: %v)", name, err)
	case v12.HelmRepositoryAssertion, *v12.HelmRepositoryAssertion:
		_, err := GetHelmRepositoryE(env, t, name)
		require.True(t, errors.IsNotFound(err), "HelmRepository %q should not exist (err: %v)", name, err)
	case v12.OCIRepositoryAssertion, *v12.OCIRepositoryAssertion:
		_, err := GetOCIRepositoryE(env, t, name)
		require.True(t, errors.IsNotFound(err), "OCIRepository %q should not exist (err: %v)", name, err)
	default:
		t.Fatalf("AssertNone: no Kind registered for assertion type %T", assertion)
	}
}
