// Code generated by assertgen. DO NOT EDIT.

package v1

import (
	v11 "github.com/fluxcd/kustomize-controller/api/v1"
	kustomize "github.com/fluxcd/pkg/apis/kustomize"
	meta "github.com/fluxcd/pkg/apis/meta"
	assert "github.com/mridang/wilhelm/assert"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CommonMetadataAssertion is the assertion struct for CommonMetadata.
type CommonMetadataAssertion struct {
	Annotations assert.Opt[map[string]string]
	Labels      assert.Opt[map[string]string]
}

// IsAssertable marks CommonMetadataAssertion as an Assertable.
func (_ CommonMetadataAssertion) IsAssertable() {}

// CrossNamespaceSourceReferenceAssertion is the assertion struct for CrossNamespaceSourceReference.
type CrossNamespaceSourceReferenceAssertion struct {
	APIVersion assert.Opt[string]
	Kind       assert.Opt[string]
	Name       assert.Opt[string]
	Namespace  assert.Opt[string]
}

// IsAssertable marks CrossNamespaceSourceReferenceAssertion as an Assertable.
func (_ CrossNamespaceSourceReferenceAssertion) IsAssertable() {}

// DecryptionAssertion is the assertion struct for Decryption.
type DecryptionAssertion struct {
	Provider           assert.Opt[string]
	ServiceAccountName assert.Opt[string]
	SecretRef          assert.Opt[*meta.LocalObjectReference]
}

// IsAssertable marks DecryptionAssertion as an Assertable.
func (_ DecryptionAssertion) IsAssertable() {}

// DependencyReferenceAssertion is the assertion struct for DependencyReference.
type DependencyReferenceAssertion struct {
	Name      assert.Opt[string]
	Namespace assert.Opt[string]
	ReadyExpr assert.Opt[string]
}

// IsAssertable marks DependencyReferenceAssertion as an Assertable.
func (_ DependencyReferenceAssertion) IsAssertable() {}

// GroupVersionAssertion is the assertion struct for GroupVersion.
type GroupVersionAssertion struct {
	Group   assert.Opt[string]
	Version assert.Opt[string]
}

// IsAssertable marks GroupVersionAssertion as an Assertable.
func (_ GroupVersionAssertion) IsAssertable() {}

// KustomizationAssertion is the assertion struct for Kustomization.
type KustomizationAssertion struct {
	TypeMeta   assert.Opt[v1.TypeMeta]
	ObjectMeta assert.Opt[v1.ObjectMeta]
	Spec       KustomizationSpecAssertion
	Status     assert.Opt[v11.KustomizationStatus]
}

// IsAssertable marks KustomizationAssertion as an Assertable.
func (_ KustomizationAssertion) IsAssertable() {}

// KustomizationSpecAssertion is the assertion struct for KustomizationSpec.
type KustomizationSpecAssertion struct {
	CommonMetadata          CommonMetadataAssertion
	DependsOn               assert.Opt[[]DependencyReferenceAssertion]
	Decryption              DecryptionAssertion
	Interval                assert.Opt[v1.Duration]
	RetryInterval           assert.Opt[*v1.Duration]
	KubeConfig              assert.Opt[*meta.KubeConfigReference]
	Path                    assert.Opt[string]
	PostBuild               PostBuildAssertion
	Prune                   assert.Opt[bool]
	DeletionPolicy          assert.Opt[string]
	HealthChecks            assert.Opt[[]meta.NamespacedObjectKindReference]
	NamePrefix              assert.Opt[string]
	NameSuffix              assert.Opt[string]
	Patches                 assert.Opt[[]kustomize.Patch]
	Images                  assert.Opt[[]kustomize.Image]
	ServiceAccountName      assert.Opt[string]
	SourceRef               CrossNamespaceSourceReferenceAssertion
	Suspend                 assert.Opt[bool]
	TargetNamespace         assert.Opt[string]
	Timeout                 assert.Opt[*v1.Duration]
	Force                   assert.Opt[bool]
	Wait                    assert.Opt[bool]
	Components              assert.Opt[[]string]
	IgnoreMissingComponents assert.Opt[bool]
	HealthCheckExprs        assert.Opt[[]kustomize.CustomHealthCheck]
}

// IsAssertable marks KustomizationSpecAssertion as an Assertable.
func (_ KustomizationSpecAssertion) IsAssertable() {}

// PostBuildAssertion is the assertion struct for PostBuild.
type PostBuildAssertion struct {
	Substitute     assert.Opt[map[string]string]
	SubstituteFrom assert.Opt[[]SubstituteReferenceAssertion]
}

// IsAssertable marks PostBuildAssertion as an Assertable.
func (_ PostBuildAssertion) IsAssertable() {}

// ResourceInventoryAssertion is the assertion struct for ResourceInventory.
type ResourceInventoryAssertion struct {
	Entries assert.Opt[[]ResourceRefAssertion]
}

// IsAssertable marks ResourceInventoryAssertion as an Assertable.
func (_ ResourceInventoryAssertion) IsAssertable() {}

// ResourceRefAssertion is the assertion struct for ResourceRef.
type ResourceRefAssertion struct {
	ID      assert.Opt[string]
	Version assert.Opt[string]
}

// IsAssertable marks ResourceRefAssertion as an Assertable.
func (_ ResourceRefAssertion) IsAssertable() {}

// SubstituteReferenceAssertion is the assertion struct for SubstituteReference.
type SubstituteReferenceAssertion struct {
	Kind     assert.Opt[string]
	Name     assert.Opt[string]
	Optional assert.Opt[bool]
}

// IsAssertable marks SubstituteReferenceAssertion as an Assertable.
func (_ SubstituteReferenceAssertion) IsAssertable() {}
