// Code generated by envgen. DO NOT EDIT.

package v1

import (
	"fmt"
	v1 "github.com/fluxcd/kustomize-controller/api/v1"
	assert "github.com/mridang/wilhelm/assert"
	v12 "github.com/mridang/wilhelm/assert/flux/kustomize/v1"
	env "github.com/mridang/wilhelm/env"
	require "github.com/stretchr/testify/require"
	errors "k8s.io/apimachinery/pkg/api/errors"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	"testing"
)

// GetKustomization fetches a Kustomization by name via the dynamic client, failing the test on error.
func GetKustomization(env *env.Env, t *testing.T, name string) *v1.Kustomization {
	t.Helper()
	obj, err := GetKustomizationE(env, t, name)
	require.NoError(t, err, "failed to get Kustomization %s", name)
	return obj
}

// GetKustomizationE fetches a Kustomization by name via the dynamic client, returning the error for non-existence checks.
func GetKustomizationE(env *env.Env, t *testing.T, name string) (*v1.Kustomization, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "kustomize.toolkit.fluxcd.io",
		Resource: "kustomizations",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.Kustomization
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert Kustomization from unstructured: %w", err)
	}
	return &out, nil
}

// AssertKustomization fetches a Kustomization and runs a partial assertion against it.
func AssertKustomization(env *env.Env, t *testing.T, name string, asn v12.KustomizationAssertion) {
	t.Helper()
	assert.Partial(t, GetKustomization(env, t, name), asn, name)
}

// AssertPartial dispatches assertion to the matching Assert<Kind> based on
// the concrete type of assertion.
func AssertPartial(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch a := assertion.(type) {
	case v12.KustomizationAssertion:
		AssertKustomization(env, t, name, a)
	case *v12.KustomizationAssertion:
		AssertKustomization(env, t, name, *a)
	default:
		t.Fatalf("AssertPartial: no Kind registered for assertion type %T", assertion)
	}
}

// AssertNone asserts that the Kind implied by assertion does not exist
// (the dynamic-client GET returns NotFound).
func AssertNone(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch assertion.(type) {
	case v12.KustomizationAssertion, *v12.KustomizationAssertion:
		_, err := GetKustomizationE(env, t, name)
		require.True(t, errors.IsNotFound(err), "Kustomization %q should not exist (err: %v)", name, err)
	default:
		t.Fatalf("AssertNone: no Kind registered for assertion type %T", assertion)
	}
}
