// Code generated by envgen. DO NOT EDIT.

package v1

import (
	"fmt"
	assert "github.com/mridang/wilhelm/assert"
	v12 "github.com/mridang/wilhelm/assert/tekton/pipeline/v1"
	env "github.com/mridang/wilhelm/env"
	require "github.com/stretchr/testify/require"
	v1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	errors "k8s.io/apimachinery/pkg/api/errors"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	"testing"
)

// GetPipeline fetches a Pipeline by name via the dynamic client, failing the test on error.
func GetPipeline(env *env.Env, t *testing.T, name string) *v1.Pipeline {
	t.Helper()
	obj, err := GetPipelineE(env, t, name)
	require.NoError(t, err, "failed to get Pipeline %s", name)
	return obj
}

// GetPipelineE fetches a Pipeline by name via the dynamic client, returning the error for non-existence checks.
func GetPipelineE(env *env.Env, t *testing.T, name string) (*v1.Pipeline, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "tekton.dev",
		Resource: "pipelines",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.Pipeline
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert Pipeline from unstructured: %w", err)
	}
	return &out, nil
}

// AssertPipeline fetches a Pipeline and runs a partial assertion against it.
func AssertPipeline(env *env.Env, t *testing.T, name string, asn v12.PipelineAssertion) {
	t.Helper()
	assert.Partial(t, GetPipeline(env, t, name), asn, name)
}

// GetPipelineRun fetches a PipelineRun by name via the dynamic client, failing the test on error.
func GetPipelineRun(env *env.Env, t *testing.T, name string) *v1.PipelineRun {
	t.Helper()
	obj, err := GetPipelineRunE(env, t, name)
	require.NoError(t, err, "failed to get PipelineRun %s", name)
	return obj
}

// GetPipelineRunE fetches a PipelineRun by name via the dynamic client, returning the error for non-existence checks.
func GetPipelineRunE(env *env.Env, t *testing.T, name string) (*v1.PipelineRun, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "tekton.dev",
		Resource: "pipelineruns",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.PipelineRun
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert PipelineRun from unstructured: %w", err)
	}
	return &out, nil
}

// AssertPipelineRun fetches a PipelineRun and runs a partial assertion against it.
func AssertPipelineRun(env *env.Env, t *testing.T, name string, asn v12.PipelineRunAssertion) {
	t.Helper()
	assert.Partial(t, GetPipelineRun(env, t, name), asn, name)
}

// GetTask fetches a Task by name via the dynamic client, failing the test on error.
func GetTask(env *env.Env, t *testing.T, name string) *v1.Task {
	t.Helper()
	obj, err := GetTaskE(env, t, name)
	require.NoError(t, err, "failed to get Task %s", name)
	return obj
}

// GetTaskE fetches a Task by name via the dynamic client, returning the error for non-existence checks.
func GetTaskE(env *env.Env, t *testing.T, name string) (*v1.Task, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "tekton.dev",
		Resource: "tasks",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.Task
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert Task from unstructured: %w", err)
	}
	return &out, nil
}

// AssertTask fetches a Task and runs a partial assertion against it.
func AssertTask(env *env.Env, t *testing.T, name string, asn v12.TaskAssertion) {
	t.Helper()
	assert.Partial(t, GetTask(env, t, name), asn, name)
}

// GetTaskRun fetches a TaskRun by name via the dynamic client, failing the test on error.
func GetTaskRun(env *env.Env, t *testing.T, name string) *v1.TaskRun {
	t.Helper()
	obj, err := GetTaskRunE(env, t, name)
	require.NoError(t, err, "failed to get TaskRun %s", name)
	return obj
}

// GetTaskRunE fetches a TaskRun by name via the dynamic client, returning the error for non-existence checks.
func GetTaskRunE(env *env.Env, t *testing.T, name string) (*v1.TaskRun, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "tekton.dev",
		Resource: "taskruns",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.TaskRun
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert TaskRun from unstructured: %w", err)
	}
	return &out, nil
}

// AssertTaskRun fetches a TaskRun and runs a partial assertion against it.
func AssertTaskRun(env *env.Env, t *testing.T, name string, asn v12.TaskRunAssertion) {
	t.Helper()
	assert.Partial(t, GetTaskRun(env, t, name), asn, name)
}

// AssertPartial dispatches assertion to the matching Assert<Kind> based on
// the concrete type of assertion.
func AssertPartial(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch a := assertion.(type) {
	case v12.PipelineAssertion:
		AssertPipeline(env, t, name, a)
	case *v12.PipelineAssertion:
		AssertPipeline(env, t, name, *a)
	case v12.PipelineRunAssertion:
		AssertPipelineRun(env, t, name, a)
	case *v12.PipelineRunAssertion:
		AssertPipelineRun(env, t, name, *a)
	case v12.TaskAssertion:
		AssertTask(env, t, name, a)
	case *v12.TaskAssertion:
		AssertTask(env, t, name, *a)
	case v12.TaskRunAssertion:
		AssertTaskRun(env, t, name, a)
	case *v12.TaskRunAssertion:
		AssertTaskRun(env, t, name, *a)
	default:
		t.Fatalf("AssertPartial: no Kind registered for assertion type %T", assertion)
	}
}

// AssertNone asserts that the Kind implied by assertion does not exist
// (the dynamic-client GET returns NotFound).
func AssertNone(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch assertion.(type) {
	case v12.PipelineAssertion, *v12.PipelineAssertion:
		_, err := GetPipelineE(env, t, name)
		require.True(t, errors.IsNotFound(err), "Pipeline %q should not exist (err: %v)", name, err)
	case v12.PipelineRunAssertion, *v12.PipelineRunAssertion:
		_, err := GetPipelineRunE(env, t, name)
		require.True(t, errors.IsNotFound(err), "PipelineRun %q should not exist (err: %v)", name, err)
	case v12.TaskAssertion, *v12.TaskAssertion:
		_, err := GetTaskE(env, t, name)
		require.True(t, errors.IsNotFound(err), "Task %q should not exist (err: %v)", name, err)
	case v12.TaskRunAssertion, *v12.TaskRunAssertion:
		_, err := GetTaskRunE(env, t, name)
		require.True(t, errors.IsNotFound(err), "TaskRun %q should not exist (err: %v)", name, err)
	default:
		t.Fatalf("AssertNone: no Kind registered for assertion type %T", assertion)
	}
}
