// Code generated by envgen. DO NOT EDIT.

package v2

import (
	"fmt"
	v2 "github.com/fluxcd/helm-controller/api/v2"
	assert "github.com/mridang/wilhelm/assert"
	v21 "github.com/mridang/wilhelm/assert/flux/helm/v2"
	env "github.com/mridang/wilhelm/env"
	require "github.com/stretchr/testify/require"
	errors "k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	"testing"
)

// GetHelmRelease fetches a HelmRelease by name via the dynamic client, failing the test on error.
func GetHelmRelease(env *env.Env, t *testing.T, name string) *v2.HelmRelease {
	t.Helper()
	obj, err := GetHelmReleaseE(env, t, name)
	require.NoError(t, err, "failed to get HelmRelease %s", name)
	return obj
}

// GetHelmReleaseE fetches a HelmRelease by name via the dynamic client, returning the error for non-existence checks.
func GetHelmReleaseE(env *env.Env, t *testing.T, name string) (*v2.HelmRelease, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "helm.toolkit.fluxcd.io",
		Resource: "helmreleases",
		Version:  "v2",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v2.HelmRelease
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert HelmRelease from unstructured: %w", err)
	}
	return &out, nil
}

// AssertHelmRelease fetches a HelmRelease and runs a partial assertion against it.
func AssertHelmRelease(env *env.Env, t *testing.T, name string, asn v21.HelmReleaseAssertion) {
	t.Helper()
	assert.Partial(t, GetHelmRelease(env, t, name), asn, name)
}

// AssertPartial dispatches assertion to the matching Assert<Kind> based on
// the concrete type of assertion.
func AssertPartial(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch a := assertion.(type) {
	case v21.HelmReleaseAssertion:
		AssertHelmRelease(env, t, name, a)
	case *v21.HelmReleaseAssertion:
		AssertHelmRelease(env, t, name, *a)
	default:
		t.Fatalf("AssertPartial: no Kind registered for assertion type %T", assertion)
	}
}

// AssertNone asserts that the Kind implied by assertion does not exist
// (the dynamic-client GET returns NotFound).
func AssertNone(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch assertion.(type) {
	case v21.HelmReleaseAssertion, *v21.HelmReleaseAssertion:
		_, err := GetHelmReleaseE(env, t, name)
		require.True(t, errors.IsNotFound(err), "HelmRelease %q should not exist (err: %v)", name, err)
	default:
		t.Fatalf("AssertNone: no Kind registered for assertion type %T", assertion)
	}
}
