// Code generated by envgen. DO NOT EDIT.

package v1

import (
	"fmt"
	assert "github.com/mridang/wilhelm/assert"
	v12 "github.com/mridang/wilhelm/assert/velero/api/v1"
	env "github.com/mridang/wilhelm/env"
	require "github.com/stretchr/testify/require"
	v1 "github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
	errors "k8s.io/apimachinery/pkg/api/errors"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	"testing"
)

// GetBackup fetches a Backup by name via the dynamic client, failing the test on error.
func GetBackup(env *env.Env, t *testing.T, name string) *v1.Backup {
	t.Helper()
	obj, err := GetBackupE(env, t, name)
	require.NoError(t, err, "failed to get Backup %s", name)
	return obj
}

// GetBackupE fetches a Backup by name via the dynamic client, returning the error for non-existence checks.
func GetBackupE(env *env.Env, t *testing.T, name string) (*v1.Backup, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "backups",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.Backup
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert Backup from unstructured: %w", err)
	}
	return &out, nil
}

// AssertBackup fetches a Backup and runs a partial assertion against it.
func AssertBackup(env *env.Env, t *testing.T, name string, asn v12.BackupAssertion) {
	t.Helper()
	assert.Partial(t, GetBackup(env, t, name), asn, name)
}

// GetBackupRepository fetches a BackupRepository by name via the dynamic client, failing the test on error.
func GetBackupRepository(env *env.Env, t *testing.T, name string) *v1.BackupRepository {
	t.Helper()
	obj, err := GetBackupRepositoryE(env, t, name)
	require.NoError(t, err, "failed to get BackupRepository %s", name)
	return obj
}

// GetBackupRepositoryE fetches a BackupRepository by name via the dynamic client, returning the error for non-existence checks.
func GetBackupRepositoryE(env *env.Env, t *testing.T, name string) (*v1.BackupRepository, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "backuprepositories",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.BackupRepository
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert BackupRepository from unstructured: %w", err)
	}
	return &out, nil
}

// AssertBackupRepository fetches a BackupRepository and runs a partial assertion against it.
func AssertBackupRepository(env *env.Env, t *testing.T, name string, asn v12.BackupRepositoryAssertion) {
	t.Helper()
	assert.Partial(t, GetBackupRepository(env, t, name), asn, name)
}

// GetBackupStorageLocation fetches a BackupStorageLocation by name via the dynamic client, failing the test on error.
func GetBackupStorageLocation(env *env.Env, t *testing.T, name string) *v1.BackupStorageLocation {
	t.Helper()
	obj, err := GetBackupStorageLocationE(env, t, name)
	require.NoError(t, err, "failed to get BackupStorageLocation %s", name)
	return obj
}

// GetBackupStorageLocationE fetches a BackupStorageLocation by name via the dynamic client, returning the error for non-existence checks.
func GetBackupStorageLocationE(env *env.Env, t *testing.T, name string) (*v1.BackupStorageLocation, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "backupstoragelocations",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.BackupStorageLocation
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert BackupStorageLocation from unstructured: %w", err)
	}
	return &out, nil
}

// AssertBackupStorageLocation fetches a BackupStorageLocation and runs a partial assertion against it.
func AssertBackupStorageLocation(env *env.Env, t *testing.T, name string, asn v12.BackupStorageLocationAssertion) {
	t.Helper()
	assert.Partial(t, GetBackupStorageLocation(env, t, name), asn, name)
}

// GetDeleteBackupRequest fetches a DeleteBackupRequest by name via the dynamic client, failing the test on error.
func GetDeleteBackupRequest(env *env.Env, t *testing.T, name string) *v1.DeleteBackupRequest {
	t.Helper()
	obj, err := GetDeleteBackupRequestE(env, t, name)
	require.NoError(t, err, "failed to get DeleteBackupRequest %s", name)
	return obj
}

// GetDeleteBackupRequestE fetches a DeleteBackupRequest by name via the dynamic client, returning the error for non-existence checks.
func GetDeleteBackupRequestE(env *env.Env, t *testing.T, name string) (*v1.DeleteBackupRequest, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "deletebackuprequests",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.DeleteBackupRequest
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert DeleteBackupRequest from unstructured: %w", err)
	}
	return &out, nil
}

// AssertDeleteBackupRequest fetches a DeleteBackupRequest and runs a partial assertion against it.
func AssertDeleteBackupRequest(env *env.Env, t *testing.T, name string, asn v12.DeleteBackupRequestAssertion) {
	t.Helper()
	assert.Partial(t, GetDeleteBackupRequest(env, t, name), asn, name)
}

// GetDownloadRequest fetches a DownloadRequest by name via the dynamic client, failing the test on error.
func GetDownloadRequest(env *env.Env, t *testing.T, name string) *v1.DownloadRequest {
	t.Helper()
	obj, err := GetDownloadRequestE(env, t, name)
	require.NoError(t, err, "failed to get DownloadRequest %s", name)
	return obj
}

// GetDownloadRequestE fetches a DownloadRequest by name via the dynamic client, returning the error for non-existence checks.
func GetDownloadRequestE(env *env.Env, t *testing.T, name string) (*v1.DownloadRequest, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "downloadrequests",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.DownloadRequest
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert DownloadRequest from unstructured: %w", err)
	}
	return &out, nil
}

// AssertDownloadRequest fetches a DownloadRequest and runs a partial assertion against it.
func AssertDownloadRequest(env *env.Env, t *testing.T, name string, asn v12.DownloadRequestAssertion) {
	t.Helper()
	assert.Partial(t, GetDownloadRequest(env, t, name), asn, name)
}

// GetPodVolumeBackup fetches a PodVolumeBackup by name via the dynamic client, failing the test on error.
func GetPodVolumeBackup(env *env.Env, t *testing.T, name string) *v1.PodVolumeBackup {
	t.Helper()
	obj, err := GetPodVolumeBackupE(env, t, name)
	require.NoError(t, err, "failed to get PodVolumeBackup %s", name)
	return obj
}

// GetPodVolumeBackupE fetches a PodVolumeBackup by name via the dynamic client, returning the error for non-existence checks.
func GetPodVolumeBackupE(env *env.Env, t *testing.T, name string) (*v1.PodVolumeBackup, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "podvolumebackups",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.PodVolumeBackup
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert PodVolumeBackup from unstructured: %w", err)
	}
	return &out, nil
}

// AssertPodVolumeBackup fetches a PodVolumeBackup and runs a partial assertion against it.
func AssertPodVolumeBackup(env *env.Env, t *testing.T, name string, asn v12.PodVolumeBackupAssertion) {
	t.Helper()
	assert.Partial(t, GetPodVolumeBackup(env, t, name), asn, name)
}

// GetPodVolumeRestore fetches a PodVolumeRestore by name via the dynamic client, failing the test on error.
func GetPodVolumeRestore(env *env.Env, t *testing.T, name string) *v1.PodVolumeRestore {
	t.Helper()
	obj, err := GetPodVolumeRestoreE(env, t, name)
	require.NoError(t, err, "failed to get PodVolumeRestore %s", name)
	return obj
}

// GetPodVolumeRestoreE fetches a PodVolumeRestore by name via the dynamic client, returning the error for non-existence checks.
func GetPodVolumeRestoreE(env *env.Env, t *testing.T, name string) (*v1.PodVolumeRestore, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "podvolumerestores",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.PodVolumeRestore
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert PodVolumeRestore from unstructured: %w", err)
	}
	return &out, nil
}

// AssertPodVolumeRestore fetches a PodVolumeRestore and runs a partial assertion against it.
func AssertPodVolumeRestore(env *env.Env, t *testing.T, name string, asn v12.PodVolumeRestoreAssertion) {
	t.Helper()
	assert.Partial(t, GetPodVolumeRestore(env, t, name), asn, name)
}

// GetRestore fetches a Restore by name via the dynamic client, failing the test on error.
func GetRestore(env *env.Env, t *testing.T, name string) *v1.Restore {
	t.Helper()
	obj, err := GetRestoreE(env, t, name)
	require.NoError(t, err, "failed to get Restore %s", name)
	return obj
}

// GetRestoreE fetches a Restore by name via the dynamic client, returning the error for non-existence checks.
func GetRestoreE(env *env.Env, t *testing.T, name string) (*v1.Restore, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "restores",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.Restore
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert Restore from unstructured: %w", err)
	}
	return &out, nil
}

// AssertRestore fetches a Restore and runs a partial assertion against it.
func AssertRestore(env *env.Env, t *testing.T, name string, asn v12.RestoreAssertion) {
	t.Helper()
	assert.Partial(t, GetRestore(env, t, name), asn, name)
}

// GetSchedule fetches a Schedule by name via the dynamic client, failing the test on error.
func GetSchedule(env *env.Env, t *testing.T, name string) *v1.Schedule {
	t.Helper()
	obj, err := GetScheduleE(env, t, name)
	require.NoError(t, err, "failed to get Schedule %s", name)
	return obj
}

// GetScheduleE fetches a Schedule by name via the dynamic client, returning the error for non-existence checks.
func GetScheduleE(env *env.Env, t *testing.T, name string) (*v1.Schedule, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "schedules",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.Schedule
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert Schedule from unstructured: %w", err)
	}
	return &out, nil
}

// AssertSchedule fetches a Schedule and runs a partial assertion against it.
func AssertSchedule(env *env.Env, t *testing.T, name string, asn v12.ScheduleAssertion) {
	t.Helper()
	assert.Partial(t, GetSchedule(env, t, name), asn, name)
}

// GetServerStatusRequest fetches a ServerStatusRequest by name via the dynamic client, failing the test on error.
func GetServerStatusRequest(env *env.Env, t *testing.T, name string) *v1.ServerStatusRequest {
	t.Helper()
	obj, err := GetServerStatusRequestE(env, t, name)
	require.NoError(t, err, "failed to get ServerStatusRequest %s", name)
	return obj
}

// GetServerStatusRequestE fetches a ServerStatusRequest by name via the dynamic client, returning the error for non-existence checks.
func GetServerStatusRequestE(env *env.Env, t *testing.T, name string) (*v1.ServerStatusRequest, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "serverstatusrequests",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.ServerStatusRequest
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert ServerStatusRequest from unstructured: %w", err)
	}
	return &out, nil
}

// AssertServerStatusRequest fetches a ServerStatusRequest and runs a partial assertion against it.
func AssertServerStatusRequest(env *env.Env, t *testing.T, name string, asn v12.ServerStatusRequestAssertion) {
	t.Helper()
	assert.Partial(t, GetServerStatusRequest(env, t, name), asn, name)
}

// GetVolumeSnapshotLocation fetches a VolumeSnapshotLocation by name via the dynamic client, failing the test on error.
func GetVolumeSnapshotLocation(env *env.Env, t *testing.T, name string) *v1.VolumeSnapshotLocation {
	t.Helper()
	obj, err := GetVolumeSnapshotLocationE(env, t, name)
	require.NoError(t, err, "failed to get VolumeSnapshotLocation %s", name)
	return obj
}

// GetVolumeSnapshotLocationE fetches a VolumeSnapshotLocation by name via the dynamic client, returning the error for non-existence checks.
func GetVolumeSnapshotLocationE(env *env.Env, t *testing.T, name string) (*v1.VolumeSnapshotLocation, error) {
	t.Helper()
	gvr := schema.GroupVersionResource{
		Group:    "velero.io",
		Resource: "volumesnapshotlocations",
		Version:  "v1",
	}
	u, err := env.DynamicClient.Resource(gvr).Namespace(env.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	if err != nil {
		return nil, err
	}
	var out v1.VolumeSnapshotLocation
	if err := runtime.DefaultUnstructuredConverter.FromUnstructured(u.Object, &out); err != nil {
		return nil, fmt.Errorf("convert VolumeSnapshotLocation from unstructured: %w", err)
	}
	return &out, nil
}

// AssertVolumeSnapshotLocation fetches a VolumeSnapshotLocation and runs a partial assertion against it.
func AssertVolumeSnapshotLocation(env *env.Env, t *testing.T, name string, asn v12.VolumeSnapshotLocationAssertion) {
	t.Helper()
	assert.Partial(t, GetVolumeSnapshotLocation(env, t, name), asn, name)
}

// AssertPartial dispatches assertion to the matching Assert<Kind> based on
// the concrete type of assertion.
func AssertPartial(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch a := assertion.(type) {
	case v12.BackupAssertion:
		AssertBackup(env, t, name, a)
	case *v12.BackupAssertion:
		AssertBackup(env, t, name, *a)
	case v12.BackupRepositoryAssertion:
		AssertBackupRepository(env, t, name, a)
	case *v12.BackupRepositoryAssertion:
		AssertBackupRepository(env, t, name, *a)
	case v12.BackupStorageLocationAssertion:
		AssertBackupStorageLocation(env, t, name, a)
	case *v12.BackupStorageLocationAssertion:
		AssertBackupStorageLocation(env, t, name, *a)
	case v12.DeleteBackupRequestAssertion:
		AssertDeleteBackupRequest(env, t, name, a)
	case *v12.DeleteBackupRequestAssertion:
		AssertDeleteBackupRequest(env, t, name, *a)
	case v12.DownloadRequestAssertion:
		AssertDownloadRequest(env, t, name, a)
	case *v12.DownloadRequestAssertion:
		AssertDownloadRequest(env, t, name, *a)
	case v12.PodVolumeBackupAssertion:
		AssertPodVolumeBackup(env, t, name, a)
	case *v12.PodVolumeBackupAssertion:
		AssertPodVolumeBackup(env, t, name, *a)
	case v12.PodVolumeRestoreAssertion:
		AssertPodVolumeRestore(env, t, name, a)
	case *v12.PodVolumeRestoreAssertion:
		AssertPodVolumeRestore(env, t, name, *a)
	case v12.RestoreAssertion:
		AssertRestore(env, t, name, a)
	case *v12.RestoreAssertion:
		AssertRestore(env, t, name, *a)
	case v12.ScheduleAssertion:
		AssertSchedule(env, t, name, a)
	case *v12.ScheduleAssertion:
		AssertSchedule(env, t, name, *a)
	case v12.ServerStatusRequestAssertion:
		AssertServerStatusRequest(env, t, name, a)
	case *v12.ServerStatusRequestAssertion:
		AssertServerStatusRequest(env, t, name, *a)
	case v12.VolumeSnapshotLocationAssertion:
		AssertVolumeSnapshotLocation(env, t, name, a)
	case *v12.VolumeSnapshotLocationAssertion:
		AssertVolumeSnapshotLocation(env, t, name, *a)
	default:
		t.Fatalf("AssertPartial: no Kind registered for assertion type %T", assertion)
	}
}

// AssertNone asserts that the Kind implied by assertion does not exist
// (the dynamic-client GET returns NotFound).
func AssertNone(env *env.Env, t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch assertion.(type) {
	case v12.BackupAssertion, *v12.BackupAssertion:
		_, err := GetBackupE(env, t, name)
		require.True(t, errors.IsNotFound(err), "Backup %q should not exist (err: %v)", name, err)
	case v12.BackupRepositoryAssertion, *v12.BackupRepositoryAssertion:
		_, err := GetBackupRepositoryE(env, t, name)
		require.True(t, errors.IsNotFound(err), "BackupRepository %q should not exist (err: %v)", name, err)
	case v12.BackupStorageLocationAssertion, *v12.BackupStorageLocationAssertion:
		_, err := GetBackupStorageLocationE(env, t, name)
		require.True(t, errors.IsNotFound(err), "BackupStorageLocation %q should not exist (err: %v)", name, err)
	case v12.DeleteBackupRequestAssertion, *v12.DeleteBackupRequestAssertion:
		_, err := GetDeleteBackupRequestE(env, t, name)
		require.True(t, errors.IsNotFound(err), "DeleteBackupRequest %q should not exist (err: %v)", name, err)
	case v12.DownloadRequestAssertion, *v12.DownloadRequestAssertion:
		_, err := GetDownloadRequestE(env, t, name)
		require.True(t, errors.IsNotFound(err), "DownloadRequest %q should not exist (err: %v)", name, err)
	case v12.PodVolumeBackupAssertion, *v12.PodVolumeBackupAssertion:
		_, err := GetPodVolumeBackupE(env, t, name)
		require.True(t, errors.IsNotFound(err), "PodVolumeBackup %q should not exist (err: %v)", name, err)
	case v12.PodVolumeRestoreAssertion, *v12.PodVolumeRestoreAssertion:
		_, err := GetPodVolumeRestoreE(env, t, name)
		require.True(t, errors.IsNotFound(err), "PodVolumeRestore %q should not exist (err: %v)", name, err)
	case v12.RestoreAssertion, *v12.RestoreAssertion:
		_, err := GetRestoreE(env, t, name)
		require.True(t, errors.IsNotFound(err), "Restore %q should not exist (err: %v)", name, err)
	case v12.ScheduleAssertion, *v12.ScheduleAssertion:
		_, err := GetScheduleE(env, t, name)
		require.True(t, errors.IsNotFound(err), "Schedule %q should not exist (err: %v)", name, err)
	case v12.ServerStatusRequestAssertion, *v12.ServerStatusRequestAssertion:
		_, err := GetServerStatusRequestE(env, t, name)
		require.True(t, errors.IsNotFound(err), "ServerStatusRequest %q should not exist (err: %v)", name, err)
	case v12.VolumeSnapshotLocationAssertion, *v12.VolumeSnapshotLocationAssertion:
		_, err := GetVolumeSnapshotLocationE(env, t, name)
		require.True(t, errors.IsNotFound(err), "VolumeSnapshotLocation %q should not exist (err: %v)", name, err)
	default:
		t.Fatalf("AssertNone: no Kind registered for assertion type %T", assertion)
	}
}
