name: Release to Github

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

defaults:
  run:
    working-directory: ./

env:
  GONOSUMDB: github.com/mridang/wilhelm/*

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install multimod
        run: go install go.opentelemetry.io/build-tools/multimod@v0.30.0

      - name: Run tests
        run: go test ./...

      - name: Run semantic-release
        uses: mridang/action-semantic-release@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
